### ISSUE TITLE
CHANGELOG for v0.0.22 missing

### ISSUE THREAD

**Issue by MichaelDeBoey** [stackworx/formik-material-ui#100]
I just saw the package is updated to `v0.0.22`, but I can't find any CHANGELOG to check out the changes.

Would you be so kind to provide us with a decent CHANGELOG please? 🙂

Thanks for all your hard work! 🙂

**Comment by cliedeman** [comment]
There are notes on the release https://github.com/stackworx/formik-material-ui/releases/tag/v0.0.22

**Comment by MichaelDeBoey** [comment]
Doh! 😓

Missed those, I'm sorry! 🙂
