### ISSUE TITLE
CheckBoxWithLabels setup

### ISSUE THREAD

**Issue by VikR0001** [stackworx/formik-material-ui#101]
For some reason my labels aren't showing up next to the checkboxes. The text of the label is in the variable `theSpecialty`, and appears as expected in `name`, etc.  Here's how I'm setting it up:

	<Field
		id={theSpecialty}
		key={"ns_" + theSpecialty}
		label={theSpecialty}
		onClick={event => onChange(event)}
		name={theSpecialty}
		checked={values['specialties'].includes(theSpecialty)}
		value={theSpecialty}
		color="primary"
		component={CheckboxWithLabel}
	/>

What am I missing?

**Comment by VikR0001** [comment]
I think I found it. This seems to work:

	<FormControlLabel
		control={
			<Field
				id={theSpecialty}
				key={"ns_" + theSpecialty}
				label={theSpecialty}
				onClick={event => onChange(event)}
				name={theSpecialty}
				checked={values['specialties'].includes(theSpecialty)}
				value={theSpecialty}
				color="primary"
				component={CheckboxWithLabel}
			/>
		}
		key={"cb_" + theSpecialty}
		label={theSpecialty}
	/>

Does that look like the best-practice way to do this?

**Comment by gildur** [comment]
You could pass the label like this:
`                
<Field
  name={name}
  component={CheckboxWithLabel}
  Label={{ label: 'Example' }}
/>
`

**Comment by prionkor** [comment]
Please add some documentation for Checkbox, CheckBoxwithLabel etc.

From the help of this issue I am using this code

```
                              <Field
                                    Label={{label: 'Remember me'}}
                                    checked={false}
                                    onChange={() => console.log('checked')}
                                    name="remember"
                                    value="1"
                                    color="primary"
                                    component={CheckboxWithLabel}
                                />
```

 Invalid prop `checked` of type `array` supplied to `ForwardRef(Checkbox)`, expected `boolean`.

I have tried with or without `checked` props but it doesn't seem to change anything.

**Comment by owlyowl** [comment]
> Please add some documentation for Checkbox, CheckBoxwithLabel etc.
> 
> From the help of this issue I am using this code
> 
> ```
>                               <Field
>                                     Label={{label: 'Remember me'}}
>                                     checked={false}
>                                     onChange={() => console.log('checked')}
>                                     name="remember"
>                                     value="1"
>                                     color="primary"
>                                     component={CheckboxWithLabel}
>                                 />
> ```
> 
> The error below happens when checkbox is checked. When checkbox is not checked `false` is returned. But upon checking the checkbox value is an empty array instead of `true`
> 
> Invalid prop `checked` of type `array` supplied to `ForwardRef(Checkbox)`, expected `boolean`.
> 
> I have tried with or without `checked` props but it doesn't seem to change anything.

Having exactly the same issue "Warning: Failed prop type: Invalid prop `checked` of type `array` supplied to `ForwardRef(SwitchBase)`, expected `boolean`."

**Comment by prionkor** [comment]
@owlyowl Thanks for confirming. I thought it was only me. I have opened a separate issue #114 . Could you please comment on their as well.

**Comment by cliedeman** [comment]
This is caused by a missing `type="checkbox"`
