### ISSUE TITLE
Required is missing

### ISSUE THREAD

**Issue by lookfirst** [stackworx/formik-material-ui#102]
![image](https://user-images.githubusercontent.com/85355/63924365-5739d080-ca72-11e9-96e8-07c9ef39633d.png)

Ideally need to pass it through from the schema.

**Comment by cliedeman** [comment]
try clicking submit or tabbing off the field

**Comment by lookfirst** [comment]
You're missing the point. TextField has a `required` property, which shows a * in the UX to the user to indicate that the field is required. 

Unfortunately, yup doesn't make it easy to get this information, but I can see it deep in the tree.

**Comment by cliedeman** [comment]
Oh, you want a custom label. That falls outside of this library. Not everyone wants the star. Material ui does not do this out of the box either

**Comment by lookfirst** [comment]
Nope, I don't want a custom label. I want to set the required property on a MUI TextField.

**Comment by cliedeman** [comment]
Hmmm. there is nothing preventing it from being passed though.

Seems to be working as expected in the sandbox? 
https://codesandbox.io/s/915qlr56rp

**Comment by lookfirst** [comment]
How is it working as expected in the sandbox? Doesn't look like the screenshot above at all.

**Comment by cliedeman** [comment]
![Screenshot 2019-08-29 at 12 39 11](https://user-images.githubusercontent.com/3578740/63933681-0b7b2d00-ca5a-11e9-9ca7-6dd8f22cf811.png)

So the placeholder is working

Can you provide a codesandbox example?

**Comment by lookfirst** [comment]
![image](https://user-images.githubusercontent.com/85355/63939305-2917b900-ca91-11e9-80fb-37b03a24d3d3.png)

**Comment by cliedeman** [comment]
did you add 

```
        <Field
          name="email"
          type="email"
          label="Email"
          required={true}
          component={UppercasingTextField}
        />```

**Comment by lookfirst** [comment]
You're not understanding, get it from the schema. Why should I have to declare it twice?

**Comment by cliedeman** [comment]
That is not a feature in formik as far I am aware. And I don’t think it belongs in the library

**Comment by lookfirst** [comment]
Of course formik doesn't know anything about MUI. That is why you created your library.

However, formik definitely knows about Yup, as it is a tightly integrated dependency for handling validation.

So you take the schema from yup, run `schema.describe()` on it and then use that output to populate the `required` property on the `<TextField/>`.

But that said, forget about it. You don't seem interested in fixing your library. I guess I'll roll my own.
