### ISSUE TITLE
Support Variants with Selects

### ISSUE THREAD

**Issue by KyruCabading** [stackworx/formik-material-ui#105]
Current implementation of Select does not support Material UI's variants, can we include it?

**Comment by cliedeman** [comment]
There is nothing in the library preventing variants from being passed through. I tested in the sandbox and it worked as expected

**Comment by razdelkinroman** [comment]
i have the same problem

**Comment by cliedeman** [comment]
Can you create a codesandbox with the issue?

**Comment by razdelkinroman** [comment]
in the sandbox the problem does not repeat, but the label is not displayed correctly.
https://codesandbox.io/s/upbeat-chandrasekhar-3bfrm

**Comment by cliedeman** [comment]
@razdelkinroman the example you sent is not using formik-material-ui?
