### ISSUE TITLE
Select box option not changing on keypress

### ISSUE THREAD

**Issue by chandra329706** [stackworx/formik-material-ui#106]
Here is the file. 

When I try to change the option using keypress, the option is not changing but working perfect when I click with mouse. 
**Expected Result :** I should be able to change the option of select box using keyboard.

`import * as React from 'react';
import { Formik, Field, Form } from 'formik';
import {
    Button,
    LinearProgress,
    MenuItem,
} from '@material-ui/core';
import { TextField } from 'formik-material-ui';

const ranges = [
    {
        value: 'none',
        label: 'None',
    },
    {
        value: '0-20',
        label: '0 to 20',
    },
    {
        value: '21-50',
        label: '21 to 50',
    },
    {
        value: '51-100',
        label: '51 to 100',
    },
];

const SelectForm = () => (
    <Formik
        initialValues={{
            select: 'none',
        }}
        onSubmit={(values, { setSubmitting }) => {
            setTimeout(() => {
                setSubmitting(false);
                alert(JSON.stringify(values, null, 2));
            }, 500);
        }}
        render={({ submitForm, isSubmitting, values, setFieldValue }) => (
            <Form>
                <Field
                    type="text"
                    name="select"
                    label="With Select"
                    select
                    helperText="Please select Range"
                    margin="normal"
                    component={TextField}
                    InputLabelProps={{
                        shrink: true,
                    }}
                >
                    {ranges.map(option => (
                        <MenuItem key={option.value} value={option.value}>
                            {option.label}
                        </MenuItem>
                    ))}
                </Field>
                <br />
                {isSubmitting && <LinearProgress />}
                <br />
                <Button
                    variant="contained"
                    color="primary"
                    disabled={isSubmitting}
                    onClick={submitForm}
                >
                    Submit
        </Button>
            </Form>
        )}
    />
);

export default SelectForm;
`

**Comment by cliedeman** [comment]
The sample [codesandbox](https://codesandbox.io/s/915qlr56rp) works correctly. Can you create an example that has the issue?
