### ISSUE TITLE
accidental type coercion ?

### ISSUE THREAD

**Issue by raphaelbadia** [stackworx/formik-material-ui#107]
Hello,

https://github.com/stackworx/formik-material-ui/blob/5aa57434d92b99d82ab541d55558311adc211773/src/TextField.tsx#L31

Is there a reason why it is `!=` ? My IDE complains about it

Thanks !

**Comment by cliedeman** [comment]
It's just to catch disabled being undefined or null

```
undefined != undefined // false
null != undefined // false
null !== undefined // true
```

it could probably be written as `disabled ? isSubmitting : disabled`

**Comment by cliedeman** [comment]
This has been fixed with nullish coalescing

**Comment by raphaelbadia** [comment]
Oh right. Thanks for the answer !
