### ISSUE TITLE
TextField loses focus on external submission

### ISSUE THREAD

**Issue by rexthefex** [stackworx/formik-material-ui#108]
I have an auto-submitting form that sends debounced network requests on every form change. The TextField loses focus whenever the submit function is triggered, I guess this is because of Formik's internal `setSubmitting(true)`.

Simple codesandbox describing the issue:
https://codesandbox.io/s/mystifying-microservice-2srb9

Workaround would be to directly call a submission function wrapped in `useCallback` in order to avoid `setSubmitting(true)`, shown here, however this skips validation cycle:
https://codesandbox.io/s/awesome-ride-mjzq9

**Comment by cliedeman** [comment]
Hey,

```
        <Field
          label="test"
          name="email"
          component={TextField}
          disabled={false}
        />
```

Make the problem go away too. But this is not a real solution.

**Comment by cliedeman** [comment]
I think this should special case should be handled in user land

```
const disabled = // only disable if user clicks submit but not when auto submitting
<Field
          label="test"
          name="email"
          component={TextField}
          disabled={false}
        />
```
