### ISSUE TITLE
Wrong proptype for `checked` for CheckboxWithLabel component

### ISSUE THREAD

**Issue by eveshum** [stackworx/formik-material-ui#109]
Hi! I noticed that when using the checkboxWIthLabel component, I get a console error saying ```index.js:1446 Warning: Failed prop type: Invalid prop `checked` of type `string` supplied to `ForwardRef(Checkbox)`, expected `boolean```

should https://github.com/stackworx/formik-material-ui/blob/master/src/Checkbox.tsx#L26 not set the value to be 'checked' or empty string? I'm not sure if that is what's causing this error.

This is what my code looks like

```<Field
                            name={setting}
                            Label={{
                              label: (
                                <span>
                                  {EMAIL_SETTINGS_LABEL[setting] || setting}
                                </span>
                              )
                            }}
                            component={CheckboxWithLabel}
                          />```

**Comment by cliedeman** [comment]
Are you using material ui 4? Please provide a sandbox with the issue and I will take a look

**Comment by eveshum** [comment]
Hi! Sorry for the delay. Yes I am using material UI 4. What is the best way to provide a sandbox?

**Comment by eveshum** [comment]
closing because I think my version was off... sorry for the trouble!
