### ISSUE TITLE
Using TypeScript, What type should Val be when using `useField<Val>(props)` ?

### ISSUE THREAD

**Issue by abcd-ca** [stackworx/formik-material-ui#116]
In TypeScript, if I use `useField(props)` without specifying the Val (generic type param), I get an error,

```
Error:(70, 34) TS2345: Argument of type '{ [x: string]: any; }' is not assignable to parameter of type 'string | (ClassAttributes<HTMLInputElement> & InputHTMLAttributes<HTMLInputElement> & FieldConfig & { ...; } & { ...; }) | (ClassAttributes<...> & ... 3 more ... & { ...; }) | (ClassAttributes<...> & ... 3 more ... & { ...; })'.
  Type '{ [x: string]: any; }' is not assignable to type 'string'.
```

I am not clear what kind of type/structure I should pass though – I get errors with the ones I've tried. ex. `useField<string>(props)`, `useField<{foo:string}>(props)`. Currently I'm getting around it with, `useField<any>(props)` but I'd rather take advantage of the feature than bypass it

**Comment by cliedeman** [comment]
The components now use useField directly
