### ISSUE TITLE
SimpleFileUpload doesn't pass className from Formik Field

### ISSUE THREAD

**Issue by jwmann** [stackworx/formik-material-ui#119]
Could be related to #98 as well.

```
<Field className="foobar" component={SimpleFileUplaod} />
```

The class name "foobar" is nowhere to be found in the rendered output.

**Comment by cliedeman** [comment]
Adding this for v2. Going to remove the duplicate label property and just force everything through Label to remove the confusion

**Comment by cliedeman** [comment]
I removed the nested div and added FormControlProps
