### ISSUE TITLE
Bad performance

### ISSUE THREAD

**Issue by SQReder** [stackworx/formik-material-ui#128]
Integration with Material UI has awfull performance in comparison with bare Formik fields.

Demo:
https://codesandbox.io/s/confident-boyd-6lhw0

**Comment by cliedeman** [comment]
@SQReder what are you comparing this against?

I tried with the previous version of this library and the material ui section performance seems to be the same

https://codesandbox.io/s/interesting-solomon-ztspt

**Comment by SQReder** [comment]
With native formik fieds without component. The first form in my demo

**Comment by cliedeman** [comment]
@SQReder The performance is about what I expect with Material-ui. It can't really match native. The missing fast field is more of an issue. I have opened an issue on the formik repo to get some more information

**Comment by SQReder** [comment]
Please link the related issue here, or mention this one in the Formik repo

**Comment by cliedeman** [comment]
@SQReder - https://github.com/jaredpalmer/formik/issues/2263

**Comment by cliedeman** [comment]
@SQReder I have reverted the changes using useField - https://github.com/stackworx/formik-material-ui/issues/111#issuecomment-584861266

You can try using FastField to see if you get any performance gains but I am going to close this out anyway as Material-UI will never be as fast as a native component
