### ISSUE TITLE
[v2] Any way to use a custom Formik Field?

### ISSUE THREAD

**Issue by MikeSuiter** [stackworx/formik-material-ui#129]
We wrap the Formik Field with our own to provide additional functionality:

1. We have a `<FieldSet/>` component that we use with nested fields so you can do:
```
<FieldSet name='a.b.c.d'>
  <Field name='z' />
</FieldSet>
```

2. We have format and normalize props for our custom `<Field/>` that converts data from/to API calls like `<Field format={timeToDate} normalize={dateToTime} .../>`

Any idea on if we can still pull this off with Formik-material-ui v2 since you no longer support using `<Field>`? 

Here is what our custom Field looks like:

```
import { FastField as FormikField, isInputEvent } from 'formik';
import * as PropTypes from 'prop-types';
import React from 'react';
import { FieldSetConsumer, formatFieldName } from './FieldSet';

const Field = ({ component: Component, name, format, normalize, useContext, onChange, validate, ...otherProps }) => (
  <FieldSetConsumer>
    {context => {
      const fieldName = formatFieldName(useContext ? context : '', name);
      return (
        <FormikField name={fieldName} normalize={normalize} validate={validate}>
          {({ field, form }) => {
            const { value } = field;

            const handleChange = eventOrValue => {
              const event = isInputEvent(eventOrValue);
              let newValue;
              if (event) {
                newValue =
                  eventOrValue.target.type === 'checkbox' ? eventOrValue.target.checked : eventOrValue.target.value;
              } else {
                newValue = eventOrValue;
              }
              newValue = normalize ? normalize(newValue) : newValue;
              const oldValue = value;

              field.onChange(eventOrValue);
              form.setFieldValue(fieldName, newValue);
              if (onChange) {
                onChange({ event: eventOrValue, field, form, newValue, oldValue });
              }
            };

            const { children, ...props } = otherProps;
            return (
              <Component
                field={{
                  ...field,
                  onChange: handleChange,
                  value: format ? format(value) : value
                }}
                form={form}
                {...props}
              >
                {typeof children === 'function' ? children({ field, form }) : children}
              </Component>
            );
          }}
        </FormikField>
      );
    }}
  </FieldSetConsumer>
);
```

**Comment by MikeSuiter** [comment]
So this is my Field v2

```
const Field = ({ component: Component, name, format, normalize, useContext, onChange, validate, ...otherProps }) => {
  const context = React.useContext(FieldSetContext);
  const fieldName = formatFieldName(useContext ? context : '', name);
  const [field, , helpers] = useField(fieldName);

  const handleChange = eventOrValue => {
    const event = isInputEvent(eventOrValue);
    let newValue;
    if (event) {
      newValue = eventOrValue.target.type === 'checkbox' ? eventOrValue.target.checked : eventOrValue.target.value;
    } else {
      newValue = eventOrValue;
    }
    newValue = normalize ? normalize(newValue) : newValue;
    const oldValue = field.value;

    // field.onChange(eventOrValue);
    helpers.setValue(newValue);
    if (onChange) {
      onChange({ event: eventOrValue, field, newValue, oldValue });
    }
  };

  const value = format ? format(field.value) : field.value;
  const { children, ...props } = otherProps;

  return (
    <Component {...field} name={fieldName} value={value} onChange={handleChange} {...props}>
      {children}
    </Component>
  );
};
```

As it is above it doesn't work because Formik MUI doesn't pass `value` and `onChange` down to MUI - https://stackworx.github.io/formik-material-ui/docs/guide/faq

If I change `<Component>` above to `<input>` or MUI `<TextField>` it works just fine. The FAQ linked above says you can use `useFieldToTextField(props, customize)` to use `onChange`, etc. but my `Component` is passed in as a prop and can be any component so that doesn't work for me. 

@cliedeman What do you think about adding a `customize` prop to `TextField`, etc. so users can use `value`, `onChange`, etc. on the component instead of having to use the helper function? For us this would help us out greatly with two things:

1. Being able to use our Field as we did with Formik v1.
2. Save us a ton of time converting all our forms from `<Field component={XyzField}>` to `<XyzField>`. Our apps are big and very form heavy so this alone would save us a lot of time and repetitive and boring tasks! 

Thanks!

**Comment by mycroes** [comment]
Can't you just replace `Field` with `TextField` (`import {TextField} from 'formik-material-ui';`)? From what I saw in the docs that's how it's supposed to work now...

**Comment by cliedeman** [comment]
@MikeSuiter I realized that preventing onChange is too restrictive. The docs and types have been updated to reflect this.

I am still one the fence about dropping and use Field and have opened this [issue](https://github.com/jaredpalmer/formik/issues/2263) to hopefully gain some more insights

I have updated the [customize component docs](https://stackworx.github.io/formik-material-ui/docs/guide/custom-component#upper-casing-field). Please take a look

**Comment by MikeSuiter** [comment]
@cliedeman For our case we have our own Field component so we can keep our code the same as v1 `<OurField component={FormikMuiTextField} />`. Our app is very form field heavy for properties so it would be a lot of work to convert every field from `<FormikField>` to `<FormikMuiField>`, but since we have our own Field don't have to do that. Others with form heavy apps might not be so lucky. 

If you look at my original post you'll see our Field component is actually using a FastField and I had the same question as you posted in your link on Formik. I don't have our form-heavy app running yet with V2, only stories, so I don't know how performance will be. It will be interesting what they say about a useFastField() hook. 

Do you have any idea on if nested useField()'s are expensive? For example we have a custom `<Field>` which uses useField() and it renders a `<FormikMuiTextField>` that uses useField() does performance degrade for large forms? 

Thanks for the detailed response and let me know if you need anything else from me.

**Comment by cliedeman** [comment]
So reading the useField source it invokes a [register](https://github.com/jaredpalmer/formik/blob/master/packages/formik/src/Field.tsx#L100) and passes a validation method. 

That means depending on when you invoke useField you may alter the validation rules un-intentionally.

I am getting close to just reverting all the hooks changes and going back to the previous API. This was an interesting experiment but unless I get a really good reason to stay with useField it's likely to happen. Also I can't think of a nice API with the current setup to insert the validation prop.

**Comment by MikeSuiter** [comment]
I'm just getting into hooks but wouldn't [this line](https://github.com/jaredpalmer/formik/blob/bb1a4e011a87c791b6c2f1e0984b0cf9f6a89fff/packages/formik/src/Field.tsx#L108) cause the validation method to be re-registered? I would hope you could use useField wherever you want but don't know if that's the case. I'm using it in my custom Field but maybe that's bad? 

I could possibly just go back to my v1 Field that used FastField.

**Comment by cliedeman** [comment]
I played around it with it a [bit](https://codesandbox.io/s/happy-aryabhata-q4ri4).

It probably shouldn't be used this way. As you can override any of these [props](https://github.com/jaredpalmer/formik/blob/804206a0e34557bd3f7630054f833777ce3828c0/packages/formik/src/Field.tsx#L20).

Some didn't work but I could change overwrite validator in my example

**Comment by MikeSuiter** [comment]
@cliedeman I'm not quite following your last post. When you say it shouldn't be used this way do you mean using useField() in FormikMui components? The Formik documentation says _"You can and should use it to build your own custom input primitives. "_. [Link](https://jaredpalmer.com/formik/docs/api/useField)

You also said that some didn't work - what did you find not to work? I [modified your sandbox](https://codesandbox.io/s/formik-usefield-55yun) changing CustomField1 to not pass validate to the final useField and it worked like I think it should have - the validate from the 2nd useField was used.

I also changed CustomField2 to act like I think most custom components should. I passed validate when creating this component and it worked just fine.

Based on your example, unless I'm missing something, it seems using multiple useField()'s is fine. What I don't know is if there's a performance impact to doing this. I'm going to try and make a real-world example using a FastField

**Comment by cliedeman** [comment]
I have reverted to the previous API style - https://github.com/stackworx/formik-material-ui/issues/111#issuecomment-584861266. Please try the beta and let me know if this works for you

**Comment by MikeSuiter** [comment]
@cliedeman I've updated to the beta and have all my code working including my custom Formik FastField that does format and normalize. My custom Formik FastField works with all the standard Formik-MUI fields but the format/normalize doesn't work with Formik-MUI pickers. I tracked down to why and it's because onChange is being omitted in the helper function.

For example this is what TextField has:

```
export interface TextFieldProps
  extends FieldProps,
    Omit<MuiTextFieldProps, 'name' | 'value' | 'error'> {}
```

but TimePicker omits the onChange (which I need for my format/normalize functionality):

```
export interface TimePickerProps
  extends FieldProps,
    Omit<MuiTimePickerProps, 'name' | 'value' | 'error' | 'onChange'> {}
```

For pickers I have my components and can easily override onChange but didn't know if you have a better solution? 

```
const TimeField = props => {
  const {
    field: { onChange }
  } = props;
  const fieldProps = fieldToTimePicker(props);

  return (
    <TimePicker
      {...fieldProps}
      onChange={onChange}
      emptyLabel={i18n('timeField.label')}
      invalidLabel={i18n('timeField.label')}
    />
  );
};
```

**Comment by cliedeman** [comment]
@MikeSuiter that is an oversight. It should be possible to override onChange.
