### ISSUE TITLE
[v2] DatePicker breaks Formik validation with SSR/Next

### ISSUE THREAD

**Issue by lando-cal** [stackworx/formik-material-ui#130]
I'm playing with NextJS  and Formik for the first time here, so my apologies if I've made a sad mistake!

When using the DatePicker component in v2, something breaks the Formik validation.. 

This worked previously, utilizing the old `<Form component={datecomponent} />` syntax.
Using the newer combined syntax though, something is awry!

I've setup a [CSB here](https://codesandbox.io/s/formik-mui-ssr-4qvor). The issue can be replicated by clicking the `NEXT` button in the first form, and then `SUBMIT` on the second form, and paying attention to the console. Also of note, the other buttons that respect the `isValid` prop will be disabled.

I'm sure my code is ugly and my use case obscure, but I'd love a solution no less!

**Comment by cliedeman** [comment]
I have reverted to the previous API style - #111 (comment). Please try the beta and let me know if this works for you

**Comment by jajourda** [comment]
# Curious About How Easily this Project can be Converted to Next.Js

I'm going through the issues that are open (and closed) to see if there are any pitfalls to trying to convert this project (which looks awesome) to a next.js project.

## Advice?

I am open to advice on how to easily port this project into a next.js setup.

## Is this an option?

I am wondering if this is a way forward within _your project..._
https://github.com/mui-org/material-ui/tree/master/examples/nextjs

**Comment by cliedeman** [comment]
@jajourda Thanks :). 

Have you tried it? Reading through the docs I can’t see anything special that would need to be done the material ui side. 

There maybe be some issues with using Formik

**Comment by jajourda** [comment]
@cliedeman, that is so helpful. Thank you for taking the time to point me in that direction. I plan on trying to fork your project and implementing next.js.

**Comment by cliedeman** [comment]
@jajourda sounds good. I will close this. Please re-open if you have more questions
