### ISSUE TITLE
[v2] Field level validation missing

### ISSUE THREAD

**Issue by aloker** [stackworx/formik-material-ui#135]
Maybe I'm missing but so far I couldn't find a way to use field-level validation with V2. The components don't have a `validate` property and `<Field/>` must not be used anymore. Are there plans to add validation back?

**Comment by cliedeman** [comment]
Good spot.

This is missing from the api.

https://jaredpalmer.com/formik/docs/api/useField#fieldinputprops-value

Ciaran

**Comment by cliedeman** [comment]
This api is back in the beta version - 2.0.0.beta.1 https://github.com/stackworx/formik-material-ui/issues/111#issuecomment-584861266
