### ISSUE TITLE
[v1] Docs went missing

### ISSUE THREAD

**Issue by mastorm** [stackworx/formik-material-ui#136]
Hey there, is there a plan to integrate the old 1.x docs into Docusaurus?
When you have large codebases, the immediate switch to v2 can take a bit and having access to the old docs would make an easier time to onboard new developers.

**Comment by cliedeman** [comment]
Hi @mastorm sorry for the churn. In all likelyhood the v2 api will revert to be the same as v1 and the migration won't be needed. Sorry for the hassle. Also v1 was never really well documented anyway

**Comment by mastorm** [comment]
Alright, thank you @cliedeman
