### ISSUE TITLE
DatePicker error

### ISSUE THREAD

**Issue by hermanc-fda** [stackworx/formik-material-ui#143]
I'm on the latest version of the formik-material-ui and formik-material-ui-picker libraries that came out yesterday and I am seeing these errors for the DatePicker:

`<Field component={DatePicker} label="label" name="date" />;`

I'm certain I'm using it right (without the DatePicker it works fine)

![image](https://user-images.githubusercontent.com/60711219/74371569-e1aa8e00-4d8d-11ea-9d44-0b22aef65170.png)
![image](https://user-images.githubusercontent.com/60711219/74371587-e96a3280-4d8d-11ea-9a4c-ee64ae46dfaa.png)
![image](https://user-images.githubusercontent.com/60711219/74371605-eff8aa00-4d8d-11ea-9a84-582a398ee02c.png)
![image](https://user-images.githubusercontent.com/60711219/74371623-f71fb800-4d8d-11ea-97cc-4f72ef868522.png)
![image](https://user-images.githubusercontent.com/60711219/74371654-069f0100-4d8e-11ea-93d9-5c5286e09e0e.png)

**Comment by cliedeman** [comment]
Can you create a sandbox that has the error?

I have updated the sandbox from the docs to the latest version and added some pickers and it all seems to work correctly.

https://codesandbox.io/s/915qlr56rp

**Comment by hermanc-fda** [comment]
Sorry I'll get to this

**Comment by hermanc-fda** [comment]
I think I found the problem. I think it had to do with not setting an initialValue in Formik. Thanks.
