### ISSUE TITLE
Switch not taking initialValue

### ISSUE THREAD

**Issue by mrjdavidfg** [stackworx/formik-material-ui#145]
The `<Switch />` is not setting to active/checked when its formik `initialValue` is `true`.

Basic example here: https://codesandbox.io/s/formik-material-ui-switch-o5rns

**Comment by cliedeman** [comment]
Adding `type=checkbox` seems to fix it

**Comment by mrjdavidfg** [comment]
You are right! Thank you.

**Comment by mrjdavidfg** [comment]
Actually, the simple Switch implementation with formik-material-ui works rigth with `type="checkbox"` prop. But I have some dynamic implementation for diferent data types. Check this project now: https://codesandbox.io/s/formik-material-ui-switch2-05rbw, this way to render the Switch is not working, even with `type="checkbox"`.

**Comment by cliedeman** [comment]
The type still needs to be on the Field

```
            <Field name="my_switch" type="checkbox">
              {fieldProps => <Switch {...fieldProps}  />}
            </Field>
```
