### ISSUE TITLE
Usage with react-number-format

### ISSUE THREAD

**Issue by semopz** [stackworx/formik-material-ui#149]
This is a continuation from #103.

Text mask seems to work fine but not the number format in the example provided. Would really appreciate a working example!
The following warning is logged:
>Warning: Formik called `handleChange`, but you forgot to pass an `id` or `name` attribute to your input:
>
>    undefined
>
>    Formik cannot determine which value to update. For more info see https://github.com/jaredpalmer/formik#handlechange-e-reactchangeeventany--void

## Reproduction
https://codesandbox.io/s/formik-material-ui-number-format-nzsmp

**Comment by cliedeman** [comment]
Here is a fixed version.

https://codesandbox.io/s/formik-material-ui-number-format-vz318

Formik needs a way to identify the target field to update so this is the quick fix:

```
    <NumberFormat
      {...other}
      getInputRef={inputRef}
      onValueChange={values => {
        onChange({
          target: {
            name: other.name,
            value: values.value,
          },
        });
      }}
      thousandSeparator
      prefix="$"
    />
```

This seems to be intentional from v4 - https://github.com/s-yadav/react-number-format#v400

**Comment by nsklyarov** [comment]
Hi.. this code doesn't work if i have initial values in form;
