### ISSUE TITLE
trying to initialize/setup this repo to work with nextjs instead of create-react-app

### ISSUE THREAD

**Issue by jajourda** [stackworx/formik-material-ui#150]
# I want to use this repo within a nextjs setup
I have commented on issue #130 , but in trying to setup a codesandbox from this repo ([see here](https://codesandbox.io/s/github/stackworx/formik-material-ui/tree/master/?fontsize=14&hidenavigation=1&theme=dark)) i realized that this repo is based on create-react-app.

![image](https://user-images.githubusercontent.com/1839603/75694168-15ceeb80-5c76-11ea-9ee0-70237bf928c6.png)

## Aren't the two approaches incompatible?
The two approaches seem incompatibly different.
### Examples

- https://blog.logrocket.com/next-js-vs-create-react-app/
- https://stackshare.io/stackups/create-react-app-vs-next-js

## Will this repo break a nextjs app?
If I include this repo in my package as the documentation suggests in the getting started section, will nextjs be broken? 
![image](https://user-images.githubusercontent.com/1839603/75695094-8de9e100-5c77-11ea-8d6a-788818ef310b.png)

### Wondering if I should just start with a nextjs starter approach (BUT I DON'T WANT TO!)
I think I'm going to try to start with your repo in the codesandbox, try to integrate next, and try to deploy to zeit to see what problems arise.

**Comment by jajourda** [comment]
# Sandbox issues
So I tried to run a code sandbox with a terminal instance to see if I could interact with node processes under the hood and ran into this issue:

![image](https://user-images.githubusercontent.com/1839603/75699400-69ddce00-5c7e-11ea-9197-7d722ce15951.png)

I forked your repo, added a sandbox.config.json file and gave the `template` property the value of `node`. I followed the instructions given in [this comment ](https://github.com/codesandbox/codesandbox-client/issues/1608#issuecomment-489460283)on a codesandbox issue.

**Comment by cliedeman** [comment]
I don’t think there is anything to be done in the library. Please re-open if there is anything else
