### ISSUE TITLE
Error upgrading from 2.0.0-alpha1 to Beta 0/1 failing with "isSubmitting of undefined"

### ISSUE THREAD

**Issue by Wombat42** [stackworx/formik-material-ui#152]
Hi,

I recently updated from the alpha version of formik-material-ui to the beta. It right away started throwing an error of "Cannot read property 'isSubmitting' of undefined"

I've created a code sandbox where you can switch between versions of formik-material-ui to see that the issue begins to happen at Beta 0. [CodeSandbox](https://codesandbox.io/s/eror-upgrading-to-formik-material-ui-beta-1-9le1m?fontsize=14&hidenavigation=1&theme=dark)

I'm likely doing something wrong. I'm fairly new to React, Formik, Material-UI, etc. and any help would be really appreciated. The sandbox is a minimal version that reproduces the structure of the code in my real project.

Thanks!

**Comment by bxtp4p** [comment]
You need to use the Formik Field component. See: https://codesandbox.io/s/eror-upgrading-to-formik-material-ui-beta-1-3rc2y

**Comment by Wombat42** [comment]
Hi,

Thank you for correcting the sample's code. I had the feeling that I was doing it wrong, and it is great to see the right way to do it.

The downside though, is that beta version behavior couples me tightly to Formik. I liked the alpha version, where all the binding appeared to be working without using a _Field_. It made it easier to reuse groups of components in places where Formik wasn't applicable. Maybe it just worked coincidentally rather than intentionally.

**Comment by cliedeman** [comment]
Hi @Wombat42 

I would have preferred it that way too but there were issues with properties available on Field that useField does not have access too.

You can read the details here https://github.com/stackworx/formik-material-ui/issues/111#issuecomment-584861266
