### ISSUE TITLE
Ability to overwrite Field props (onChange, onBlur, name, etc) when needed

### ISSUE THREAD

**Issue by samuelcastro** [stackworx/formik-material-ui#161]
This is not a bug, it's more a feature request change, I'm using this lib for a while and in a few specific scenarios I want to overwrite the `onChange` prop to add a few custom behaviours that I need, however this is not allowed with the current implementation, by the simple fact that `field` props will overwrite any `component` props.

What I need is something like this:
```typescript
const FormTextField: React.FC<TextFieldProps> = props => (
  <FormikField component={TextField} {...props} />
);

<FormTextField
    name="country"
    variant="outlined"
    required
    fullWidth
    label="Country"
    onChange={myCustomOnChange}
/>
```
So I need to add a custom `onChange` that will manually call formik's [handleChange](https://jaredpalmer.com/formik/docs/api/formik#handlechange-e-reactchangeeventany--void)

I think this might be useful for others users as well, oftentimes we might need to add some custom action before actually change the input state.

I changed this behaviour in my own fork of this project that can be seen here: https://github.com/samuelcastro/formik-material-ui/commit/6c7e0e7fbe720def9344a8bcb9057a9454a4294b or installed with [@samuelcastro/formik-material-ui](https://www.npmjs.com/package/@samuelcastro/formik-material-ui)

If you think this might make sense for you let me know I'd be glad to create a PR.

Thanks!

**Comment by KieranDotCo** [comment]
I've just ran into the same problem on my project @samuelcastro I think this change makes sense if people are overriding the `onChange` they should know to handle the `setFieldValue` logic

👍

**Comment by kgilski** [comment]
I have been using this workaround to overcome this case.
```ts
import { TextField as MuiTextField } from "@material-ui/core";
import { fieldToTextField } from "formik-material-ui";

const CustomTextField: React.FC<FastFieldProps> = props => {
  const { field, form, meta, children, ...rest } = props;
  return <MuiTextField {...fieldToTextField(props)} {...rest} />;
};
```
It would be nice to see it in he official support.

**Comment by cliedeman** [comment]
Fixed in latest version
