### ISSUE TITLE
Possible to change Select transition?

### ISSUE THREAD

**Issue by jimmiejackson414** [stackworx/formik-material-ui#163]
Thanks for the incredibly helpful library!

I was wondering if it's possible to change the Select transition from the default to a Fade? Similar to the way I've added a mask for a TextField by using `inputProps`, I was hoping to achieve something along the lines of this:

```
<Field
    component={Select}
    color="primary"
    name="BillingCountry"
    inputProps={{ transitionComponent: 'Fade' }}
>
    {countries.map((country, index) => (
         <MenuItem key={index} value={country.name}>
             {country.name}
         </MenuItem>
     ))}
</Field>
```

**Comment by cliedeman** [comment]
@jimmiejackson414 We pass the props on the field mostly directly through to the material-ui compoment. If it supports the prop it should work. That being said I dont find `transitionComponent` anywhere in the docs combined with a TextField. Do you have an example or a link?

**Comment by jimmiejackson414** [comment]
It's been awhile since I looked at this, let me see if I can remember...

I think it'd actually be `MenuProps` which does exist in the [Select API](https://material-ui.com/api/select/), and the [Menu API](https://material-ui.com/components/menus/#change-transition) shows a `TransitionComponent` prop that allows you to change it.

**Comment by cliedeman** [comment]
@jimmiejackson414 We don't restrict any properties pass through to Material-UI, unfortunately this just does not seem to possible with the current api
