### ISSUE TITLE
Disabled property is not propagated

### ISSUE THREAD

**Issue by discretize** [stackworx/formik-material-ui#17]
Hi there,

if the `disabled` property is passed to a component, the value is ignored as only `isSubmitting` is taken into consideration.

See this snippet:

```js
  ({ field, form: { isSubmitting }, ...props }) => ({
    disabled: isSubmitting,
```

Therefore it is impossible to disable a component by hand.

**Comment by cliedeman** [comment]
Thanks for this, I will be more careful in future with default props.

Release in 0.0.6

**Comment by discretize** [comment]
Sure, thanks for the quick merge!
