### ISSUE TITLE
Switch and Checkbox starts inversed

### ISSUE THREAD

**Issue by pedroalves0030** [stackworx/formik-material-ui#170]
In the [codesandbox example](https://codesandbox.io/s/915qlr56rp) the `rememberMe` initial value is `true` but both the Switch and Checkbox components doesn't render accordingly.

**Comment by cliedeman** [comment]
@pedroalves0030 Thanks for reporting this

```
<Field component={Switch} type="checkbox" name="rememberMe" />
```

The type field was missing
