### ISSUE TITLE
InputBase wrapper crashes app when submitting with keyboard Enter - Cannot read property 'persist' of undefined

### ISSUE THREAD

**Issue by jeffvandyke** [stackworx/formik-material-ui#172]
Code Sandbox Reproduction: <https://codesandbox.io/s/github/jeffvandyke/formik-mui-input-base-bug/tree/master/> - the submit button works, but when enter is pressed inside the input, the app crashes with `TypeError - Cannot read property 'persist' of undefined`.

During inspection, it appears to be linked with InputBase's calling `onBlur()` with no event so that users can use it to get notified about blurring even when it's disabled (which Formik does on submit) - see [InputBase.js:248](https://github.com/mui-org/material-ui/blob/aa366d333798843eab2600dfd33fe365b4acbe92/packages/material-ui/src/InputBase/InputBase.js#L248)

The code works fine when `InputBase` is swapped out for `TextField` - field blurs properly and updates UI.

**Comment by jeffvandyke** [comment]
I've come up with a workaround - wrapping InputBase in a FixedInputBase that doesn't call onBlur if it's empty. It'd be nice if this was fixed in the library though.

```typescript.tsx
import * as React from 'react';
import { Field } from 'formik';
import { InputBase } from '@material-ui/core';
import {
  fieldToInputBase,
  InputBaseProps as FmuiInputBaseProps,
} from 'formik-material-ui';

const FixedInputBase: React.FC<FmuiInputBaseProps> = ({ onBlur, ...props }) => {
  const fmuiProps = fieldToInputBase(props);

  const handleBlur = React.useCallback(
    (e?: React.FocusEvent<HTMLInputElement | HTMLTextAreaElement>) => {
      // InputBase invokes onBlur() with no event argument when disabled,
      // presumably for other Mui components' state tracking, but it causes
      // Formik to flip out and crash the app... unless we stop this madness!
      e && fmuiProps.onBlur && fmuiProps.onBlur(e);
    },
    [fmuiProps.onBlur],
  );
  return (
    <InputBase
      {...fmuiProps}
      onBlur={fmuiProps.onBlur ? handleBlur : undefined}
    />
  );
};
```
Usable as: `<Field component={FixedInputBase} {...otherPropsHere} />`

**Comment by cliedeman** [comment]
@jeffvandyke thanks for the investigation.

Looks like we should intercept the onBlur and if the event is null rather pass in the [field name](https://github.com/formik/formik/blob/v2.1.4/packages/formik/src/Formik.tsx#L716)

**Comment by cliedeman** [comment]
Fixed in https://github.com/stackworx/formik-material-ui/pull/193
