### ISSUE TITLE
How to set the size of the select component？

### ISSUE THREAD

**Issue by bihongbin3027** [stackworx/formik-material-ui#175]
How to set the size of the select component？
`<Field
                    labelId="company"
                    name="company"
                    variant="outlined"
                    component={Select}
                  >
                    <MenuItem value={1}>name1</MenuItem>
                    <MenuItem value={2}>name2</MenuItem>
                    <MenuItem value={3}>name3</MenuItem>
                  </Field>`

**Comment by cliedeman** [comment]
@bihongbin3027 what do you mean by size?

**Comment by bihongbin3027** [comment]
> @bihongbin3027 what do you mean by size?

Select component size cannot be set.
