### ISSUE TITLE
AutoComplete - Add `getOptionValue`

### ISSUE THREAD

**Issue by michal-ciechan** [stackworx/formik-material-ui#184]
I am wondering if it is worth me creating a PR for an additional property of `AutoComplete` (`FormikMaterialUIAutocomplete`) which is used to retrieve the value from the AutoComplete option which is going to be used to set the Formik field value.

From my experience, the projects I have worked on, the entities/dto's/viewmodels usually have an `Id` field referencing another entity that gets updated, rather than the name/option value.

e.g.

```javascript
const invoice = {
  customerId: number
}
```

but in the Autocomplete, we expect you to select a `Customer` by his name. 

Therefore we set the options to be:

```javascript
const options = [
 {
    id: 1,
    name: "Microsoft"
 },
 {
    id: 2,
    name: "Facebook"
 }  
]
```
And render `name` as the option label.

Locally I have extended your code by adding a `getOptionValue` (could be `getOptionFieldValue`?) function prop which is used to retrieve the optionValue that should be stored in the `formik` `field.value`.

If this is something you would be interested in merging, let me know, I can clean up the code + create some tests/stories for it.

**Comment by cliedeman** [comment]
@michal-ciechan I thought this might be too opinated for a library but now I have another reason we can't add a default.

Free solo seems to only work with text options and when no `getOptionValue` prop is provided. Atleast I could not get it to work

**Comment by otaviobps** [comment]
@michal-ciechan would you mind sharing your solution? I want to achieve exactly the same, but I'm having some trouble with the option label

**Comment by michal-ciechan** [comment]
What I did was have a wrapper `AutoCompleteKeyed` component that takes a `parent` object, and the "key" of the ID property you want to set.

I separately keep in sync the `AutoComplete.selectedItem` via local state, and provide `AutoComplete.onSelectedItemChanged` which, updates the local selectedItem state (so it updates the AutoComplete), and also updates `parent[key] = selectedItem?.Id`.

Also, on first render, I initialise the `selectedItem` based on the `parent[key]` property.

**Comment by otaviobps** [comment]
Nice, I ended up writing my own wrapper as well. If anyone needs an example, here it is:

```typescript jsx
import { fieldToAutocomplete, AutocompleteRenderInputParams } from 'formik-mui';
import Autocomplete from '../../Autocomplete/Autocomplete';
import React, { useCallback, useMemo } from 'react';
import { AutocompleteProps } from './Autocomplete.props';
import { AutocompleteValue, TextField } from '@mui/material';

const FormikMuiAutocomplete = <
  T,
  Multiple extends boolean | undefined,
  DisableClearable extends boolean | undefined,
  FreeSolo extends boolean | undefined
>(
  props: AutocompleteProps<T, Multiple, DisableClearable, FreeSolo>
) => {
  const { label, field, form, optionLabelKey, optionValueKey, options, multiple, freeSolo, ...rest } = props;

  const { name, value, onBlur } = field;
  const { touched, errors, setFieldValue } = form;

  const renderInput = useCallback(
    (props: AutocompleteRenderInputParams) => (
      <TextField
        {...props}
        name={name}
        error={touched[name] && !!errors[name]}
        helperText={touched[name] && errors[name]}
        label={label}
      />
    ),
    [label, errors, name, touched]
  );

  const handleChange = useCallback(
    (
      event: React.SyntheticEvent,
      value: AutocompleteValue<T, Multiple, DisableClearable, FreeSolo> | string | string[]
    ) => {
      // handles multiple
      if (value && Array.isArray(value) && optionValueKey) {
        setFieldValue(
          name,
          (value as Array<any>).map((option) => option?.[optionValueKey] || option)
        );
        return;
      }

      // handles single
      if (value && optionValueKey && typeof value === 'object' && (value as any).hasOwnProperty(optionValueKey)) {
        setFieldValue(name, (value as any)[optionValueKey]);
        return;
      }

      // default
      setFieldValue(name, value);
    },
    [name, optionValueKey, setFieldValue]
  );

  const handleBlur = useCallback(
    (event: React.FocusEvent<HTMLInputElement>) => {
      const input = event.target.value;
      // call handleChange freeSolo when removing focus
      if (freeSolo && input) {
        if (multiple) {
          handleChange(event, [...value, input]);
        } else {
          handleChange(event, input);
        }
      }
      onBlur && onBlur(event);
    },
    [freeSolo, handleChange, onBlur, value, multiple]
  );

  const getOptionLabel = useCallback(
    (option) => {
      if (optionLabelKey) {
        return option?.[optionLabelKey] || option;
      }
      return option;
    },
    [optionLabelKey]
  );

  const componentValue = useMemo(() => {
    // handles multiple
    if (value && Array.isArray(value) && optionValueKey && multiple) {
      return value.map((option: string) => options?.find((o) => (o as any)?.[optionValueKey] === option) || option);
    }

    if (optionValueKey) {
      if (multiple) {
        return options?.find((option) => (option as any)?.[optionValueKey] === value) || [];
      }
      return options?.find((option) => (option as any)?.[optionValueKey] === value) || value;
    }
    return value;
  }, [optionValueKey, options, value, multiple]);

  return (
    <Autocomplete
      {...fieldToAutocomplete({ ...rest, form, field, options, multiple, freeSolo, renderInput })}
      onChange={handleChange}
      value={componentValue}
      getOptionLabel={getOptionLabel}
      onBlur={handleBlur}
      clearOnBlur
    />
  );
};

export default FormikMuiAutocomplete;

```

So when using it, you just need to provide two props:

> `optionValueKey`: the key of the value in the array of objects (options);
> `optionValueLabel`: the key of the label in the array of objects (options);

This way, everything is handled by the wrapper
