### ISSUE TITLE
TypeError: Cannot read property 'isSubmitting' of undefined

### ISSUE THREAD

**Issue by aidoskz** [stackworx/formik-material-ui#185]
![image](https://user-images.githubusercontent.com/4894700/86380859-6a2eba00-bcae-11ea-89cb-7200c39b7559.png)

![image](https://user-images.githubusercontent.com/4894700/86380930-85012e80-bcae-11ea-936d-a4af1a97b5c7.png)

```
TypeError: Cannot read property 'isSubmitting' of undefined
fieldToTextField
src/TextField.tsx:12
   9 |     Omit<MuiTextFieldProps, 'name' | 'value' | 'error'> {}
  10 | 
  11 | export function fieldToTextField({
> 12 |   disabled,
  13 |   field,
  14 |   form: { isSubmitting, touched, errors },
  15 |   ...props
View compiled
FormikMaterialUITextField
src/TextField.tsx:31
  28 | }
  29 | 
  30 | export function TextField({ children, ...props }: TextFieldProps) {
> 31 |   return <MuiTextField {...fieldToTextField(props)}>{children}</MuiTextField>;
  32 | }
  33 | 
  34 | TextField.displayName = 'FormikMaterialUITextField';
View compiled

```

versions: 

formik-material-ui-lab@^0.0.2:
  version "0.0.2"

formik-material-ui@^2.0.1:
  version "2.0.1"

formik@^2.1.4:
  version "2.1.4"

"@material-ui/core@^4.2.1":
  version "4.10.2"

"@material-ui/lab@4.0.0-alpha.33":
  version "4.0.0-alpha.33"

react@^16.12.0, react@^16.8.6:
  version "16.13.1"

npm -v
6.13.4

node -v
v10.19.0

https://github.com/stackworx/formik-material-ui/blob/60a763371a8e59355f2acdc00f5159a1ec687c20/packages/formik-material-ui/src/TextField.tsx#L14

**Comment by cliedeman** [comment]
TextField should the standard material ui component. Not the one imported from formik-material-ui

**Comment by HyperNike** [comment]
> TextField should be the standard material ui component. Not the one imported from formik-material-ui

Correct me if wrong... but the standard material ui TextField does not work with formik/yup. I ran into the same problem as I was directed to using the formik-material-ui Textfield when I found that the standard TextField was not an option.

**Comment by eddskt** [comment]
2024 using the updated versions of formik and material and no solution? have you abandoned the project?!
