### ISSUE TITLE
AutoComplete no longer honors initial value

### ISSUE THREAD

**Issue by youngbob** [stackworx/formik-material-ui#189]
#188 added support for `freeSolo`, but broke the ability to set an initial value for the AutoComplete component.
This is probably due to: https://github.com/stackworx/formik-material-ui/commit/d518eea34514312b6d2704445f49b165f109893d#diff-bfb264d78f80f3f88b1d3bdfd48835c3R63

Working (0.0.2): https://codesandbox.io/s/unruffled-sinoussi-oc9tk
Not working (0.0.3): https://codesandbox.io/s/zealous-bush-thtez

**Comment by cliedeman** [comment]
Fixed in https://github.com/stackworx/formik-material-ui/pull/190/files

**Comment by youngbob** [comment]
Fixed in 0.0.4. Thanks!
