### ISSUE TITLE
Error when using the `as` prop on <Field>

### ISSUE THREAD

**Issue by ZizhengTai** [stackworx/formik-material-ui#194]
# Background
The `component` and `render` props are deprecated in Formik in favor of `as`: https://github.com/formik/formik/pull/1406

# Issue
I tried to use `as` like this:
```
import { Field, Form, Formik } from 'formik';
import { TextField } from 'formik-material-ui';

...
  <Field
    as={TextField}
    ...
```
which produces this error:
<img width="1025" alt="Screen Shot 2020-07-14 at 4 42 06 AM" src="https://user-images.githubusercontent.com/5204568/87421829-6d6a5580-c58c-11ea-9458-4d7e5819e051.png">

Not really sure what's going on here. Using `as` with plain Formik and MUI works without errors.

**Comment by cliedeman** [comment]
Try 

```
<Field
    component={TextField}
```

**Comment by ZizhengTai** [comment]
@cliedeman , `component` does work, but I was intentionally trying to switch to `as` since `component` is being deprecated in Formik.

**Comment by cliedeman** [comment]
@ZizhengTai I think only `render` is deprecated based on the docs - https://formik.org/docs/api/field

But it does not seem to be [clear at all](https://github.com/formik/formik/issues/2561#issuecomment-650821505)

I dont think we can support as unfortunately as the mergine of [field and props](https://github.com/formik/formik/blob/master/packages/formik/src/Field.tsx#L223)
will cause the material ui onChange and onBlur to always overwrite the formik onChange and onBlur functions which we need

**Comment by dsgriffin** [comment]
[#2618](https://github.com/formium/formik/pull/2618) might be worth following here as it'll confirm whether the `component`-being-deprecated note was just a mistake or not. I'm not getting any warnings for it unlike `render`.

**Comment by cliedeman** [comment]
Thanks @dsgriffin, I dont think there is anything to be done here in the library
