### ISSUE TITLE
Autocomplete freeSolo list behaviour is broken when component has an initialValue

### ISSUE THREAD

**Issue by MKrapalis** [stackworx/formik-material-ui#197]
Without an initialValue the list works as intended in freeSolo mode and only shows the filtered list elements when entering a value in the TextField. 

![image](https://user-images.githubusercontent.com/52918053/87755399-381d6c00-c807-11ea-8593-88fb37f37f75.png)

It won't filter anymore with an initialValue.

![image](https://user-images.githubusercontent.com/52918053/87755493-6307c000-c807-11ea-8b7b-ab7046c2b608.png)

**Comment by cliedeman** [comment]
@MKrapalis I need to take a closer look at this. I tried several variations of onChange and onInputChange in the code but I could not get it to work properly.

**Comment by JohnPhoto** [comment]
I had (atleast a similar, let me know if it not the same problem so I can open a new issue) problem with autocomplete not working with initial values.
For me it boiled down to that in freeSolo-mode the getOptionLabel get passed the (controlled) values from input all the time! So what I ended up doing was defining my getOptionLabel function like this and then things just started working.

````tsx
type Option = {
  id: number;
  name?: string;
}
...

<Field
  freeSolo
  getOptionLabel={(option?: string | Option) => {
    // This function is getting called by both the renderer for Options
    // BUT ALSO the raw string value from field/input in freeSolo mode
    // So we must return the actual string if that is the case
    // otherwise the value will be reset on basically every edit to empty string

     if(typeof option === 'string'){ 
       return option;
    }
    return option?.name || ''
 }}

````

@cliedeman is it a known fact that the getOptionLabel is called by "stuff" that is not an actual Option?

**Comment by JohnPhoto** [comment]
Ok I think I actually found it:

Formik field.value should be mapped over to AutoComplete.inputValue

see changes in AutoComplete.tsx:

```
  const {
    onChange: _onChange,
    onBlur: _onBlur,
    multiple: _multiple,
   value: inputValue, // <-- Added this line
    ...fieldSubselection
  } = field;

  return {
   inputValue,
   freeSolo
   ...
```

**Comment by cliedeman** [comment]
@JohnPhoto I managed to fix this by removing the default inputChangeHandler.

Please try 0.0.6 a try and let me know if it fixes this for you. I did find what I believe to be a bug in Material UI though where the options are not filtered when an initial value is used

**Comment by JohnPhoto** [comment]
0.0.6 Works for me! Thank you for a very quick feedback and fix. Will follow the mui-org/material-ui#23102
