### ISSUE TITLE
How to add multiple file select option in SimpleFileUpload

### ISSUE THREAD

**Issue by NitinMagdum** [stackworx/formik-material-ui#198]
i am using SimpleFileUpload to upload multiple files but its not working

import { TextField, SimpleFileUpload } from 'formik-material-ui';
<Field name="file" id="file" type="file" label="Select File(s)" component={SimpleFileUpload } inputProps={{ multiple: true }} />;

**Comment by cliedeman** [comment]
Hi @NitinMagdum the SimpleFileUpload only handles a single file by design.

For more complicated use cases I suggest you use https://www.npmjs.com/package/material-ui-dropzone

**Comment by NitinMagdum** [comment]
@cliedeman Thanks

**Comment by NitinMagdum** [comment]
Thanks

**Comment by agitated5** [comment]
> Thanks





https://druid-ismael.github.io/bryson441/
