### ISSUE TITLE
TextArea support

### ISSUE THREAD

**Issue by Mir1001** [stackworx/formik-material-ui#200]
Can you provide a tip/or example how can we create a TextArea formik field with material design based on TextField? Thx

**Comment by zaksabeast** [comment]
formik-material-ui passes props down to the material-ui components, so [the multiline prop](https://material-ui.com/api/text-field/#props) should work like normal:
```jsx
<Field
  component={TextField}
  label='Textarea'
  name='textarea-example'
  multiline
/>
```

**Comment by Mir1001** [comment]
It works! Set field para rows="5" to see the difference.
