### ISSUE TITLE
useFormik example

### ISSUE THREAD

**Issue by stefensuhat** [stackworx/formik-material-ui#202]
Thanks for making us easier using formik and material-ui. I keep failing integrate useFormik and the TextField come from package. 

on example it needed `<Field />` from formik but useFormik can't use that. 

how to use the component with useFormik?

**Comment by semy** [comment]
This package in no way prevents the useFormik hook from being used. I use the hook myself a lot in my projects. Perhaps you will deal with the subject of hooks and context again in detail.

**Comment by sebdec** [comment]
I failed to make it work with hooks.
Always the same error but maybe I did it wrong ?
codesandbox: https://codesandbox.io/s/gifted-knuth-wv453

**Comment by cliedeman** [comment]
From the [docs](https://formik.org/docs/api/useFormik)

It seems there components are infact incompatible with useFormik

```
** Be aware that <Field>, <FastField>, <ErrorMessage>, connect(), and <FieldArray> will NOT work with useFormik() as they all require React Context.
```
