### ISSUE TITLE
SimpleFileUpload Remove file name from the input

### ISSUE THREAD

**Issue by dakshsaraf** [stackworx/formik-material-ui#204]
How to remove the filename that is shown when a file is uploaded using SimpleFileUpload

![Screenshot from 2020-08-01 23-49-49](https://user-images.githubusercontent.com/25619616/89107907-e7864f80-d451-11ea-81d8-598c329ec168.png)

I want to get rid of the text after the Choose File button

**Comment by cliedeman** [comment]
Hi @dakshsaraf for anything more complicated than a super basic file upload I suggest you use https://www.npmjs.com/package/material-ui-dropzone.

Styling the native file input is tricky

**Comment by dakshsaraf** [comment]
I got this done by hiding that DOM element for the input file and passing an inputRef to it.

That inputRef was accessed by another button that I added and called ref.current.click() when that button was clicked
