### ISSUE TITLE
Select component fails to display error upon validation failure

### ISSUE THREAD

**Issue by DewangS** [stackworx/formik-material-ui#205]
I have a selection list which is mandatory. The key values are numbers ranging from 1 to 11. I've added 0th element in the list with a key value as "0" (zero) and display menu item as "Select a campus ...". .. see below where campuses is an array of all valid options

 <FormControl fullWidth>
                      <InputLabel htmlFor="permit.primaryCampus">
                        Primary Campus
                      </InputLabel>

                      <Field
                        component={Select}
                        required
                        name="permit.primaryCampus"
                        id="primaryCampus"
                        inputProps={{
                          id: "primaryCampus",
                        }}
                      >
                        **<MenuItem value="0">Select primary campus...</MenuItem>**
                        {campuses.map((option) => (
                          <MenuItem value={option.value} key={option.value}>
                            {option.key}
                          </MenuItem>
                        ))}
                      </Field>
                    </FormControl>

I use Yu[p for validation with below schema which does stop form from being submitted if the campus is not selected though the 'Field' element doesn't display any error text .. the same validation works perfectly fine with simple text input fields. I think this is a bug unless I am missing something obvious

primaryCampus: Yup
    .string()
    .test( (val) => {
    //if the selected value is zero, it's an invalid selection
        if(val==="0")
        {
          return true;
        }
        
    }).required("Required"),

**Comment by cliedeman** [comment]
See https://stackworx.github.io/formik-material-ui/docs/guide/faq/#validation-errors-missing-from-select

**Comment by DewangS** [comment]
Thanks @cliedeman 

I just tried that and got below exception ... there are more lines in the exception which I've cut off due to the size

TypeError: Failed to construct 'Text': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
renderWithHooks
node_modules/react-dom/cjs/react-dom.development.js:14803
  14800 |   }
  14801 | }
  14802 | 
> 14803 | var children = Component(props, secondArg); // Check if there was a render phase update
        | ^  14804 | 
  14805 | if (workInProgress.expirationTime === renderExpirationTime) {
  14806 |   // Keep rendering in a loop for as long as render phase updates continue to
View compiled
mountIndeterminateComponent
node_modules/react-dom/cjs/react-dom.development.js:17482
  17479 | 
  17480 |   setIsRendering(true);
  17481 |   ReactCurrentOwner$1.current = workInProgress;
> 17482 |   value = renderWithHooks(null, workInProgress, Component, props, context, renderExpirationTime);
        | ^  17483 |   setIsRendering(false);
  17484 | } // React DevTools reads this flag.

**Comment by DewangS** [comment]
when I tried the second example ....see below... I get an error with value element MUST be an array

import { ErrorMessage } from 'formik';

<Field component={Select} type="text" name="tags" multiple={true}>
  <MenuItem value="dogs">Dogs</MenuItem>
  <MenuItem value="cats">Cats</MenuItem>
  <MenuItem value="rats">Rats</MenuItem>
  <MenuItem value="snakes">Snakes</MenuItem>
</Field>
<ErrorMessage name="tags" />


error ........

**Error: Material-UI: The `value` prop must be an array when using the `Select` component with `multiple`.
▶ 18 stack frames were collapsed.**
Module../src/index.js
src/index.js:5
  2 | import ReactDOM from 'react-dom';
  3 | import App from './App';
  4 | 
> 5 | ReactDOM.render(
  6 |   <React.StrictMode>
  7 |     <App />
  8 |   </React.StrictMode>,
View compiled
__webpack_require__
/Users/dewang/parking-permit/webpack/bootstrap:784
  781 | };
  782 | 
  783 | // Execute the module function
> 784 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  785 | 
  786 | // Flag the module as loaded
  787 | module.l = true;
View compiled
fn
/Users/dewang/parking-permit/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
1

**Comment by DewangS** [comment]
ok, it's all sorted now. thanks for your help. Much appreciated.

**Comment by DewangS** [comment]
The ONLY issue I have is about the error text which by default uses the "name" value of the element being validated e.g. in my case I have below JSON schema as my initialValues

`const initialValues = {
  applicantID: "",
  applicantTypeID: "1",
  firstName: "",
  lastName: "",
  email: "user@westernsydney.edu.au",
  address1: "",
  address2: "",
  suburb: "",
  state: "NSW",
  postcode: "",
  phone: "",
  mobile: "",
  business_unit_school: "",
  building: "",
  level: "",
  room: "",
  applicationStatusID: "1",
  vehicles: [
    { registrationNumber: "", make: "", model: "" },
    { registrationNumber: "", make: "", model: "" },
  ],
  permit: {
    primaryCampus: 0,
    permitType: 0,
    paymentMethod: 0,
    approvalCode: "",
  },
};`

Now, when Yup validates either the priamryCampus, permitType or paymentMethod (all are select type), in the error you will see "permit.primaryCampus is invalid", "permit.permitType is invalid" etc and this is due to how Yup validation is automatically tied up with HTML element and schema element names i.e. the element name MUST match with your initialSchema but for some reason in these error messages (for select lists) I can't override the error message text to some sort of custom message like "Required" without having the name of the element in it. I've various other TextInput (Field with component={TextInput} ) and I can easily override the error message in Yup validation schema....

**Comment by jacksonblankenship** [comment]
I'm having the exact same error as you for the first option:

`TypeError: Failed to construct 'Text': Please use the 'new' operator, this DOM object constructor cannot be called as a function.`

Using the manual option `ErrorMessage` works for validation but it does not use the error styling.
