### ISSUE TITLE
example to useRef

### ISSUE THREAD

**Issue by Wax6610** [stackworx/formik-material-ui#214]
Hello. Thank you for this component.
I need to determine the current cursor position in a textfield.
I found example with useRef hook and selectionStart property. But it doesn't work when i use innerRef prop on <Field> element, I get ref, but there is no selectionStart  property . Can i get example how to use useRef right ?

**Comment by cliedeman** [comment]
Hi @Wax6610, it would be the same as not using formik-material-ui

```typescript
<Field
              component={TextField}
              type="password"
              label="Password"
              name="password"
              InputProps={{
                inputRef=...
              }}
            />
```

**Comment by Wax6610** [comment]
Thank you, its worked
