### ISSUE TITLE
Multiple Select editing object array does not work.

### ISSUE THREAD

**Issue by naudej** [stackworx/formik-material-ui#215]
Hi, awesome work on this package by the way. Im currently struggling with a multiple select that takes in an array of values and then adds/removes the selected options.

**Problem:** 
The multi-select field takes in an initial value object array, when selecting a value via menu the already selected values arent highlighted and when an option that is already part of the initial values is selected then it re-adds it to the list. Is there any possible work around or is it something im doing wrong?

`  const initialValues = {
    activeUsers: [    
      {name: 'John Test', id: 0},
      {name: 'Jacques Virtual', id: 1},
    ]
  }

  const userArr = [
    {name: 'John Test', id: 0},
    {name: 'Jacques Virtual', id: 1},
    {name: 'Ben Form', id: 2}
  ]

          <Formik
            initialValues={initialValues}
            onSubmit={onSubmit}
          >
            {(props) => {
              const {
                values,
                touched,
                errors,
                handleBlur,
                handleChange,
                isSubmitting,
                handleReset
              } = props
              return (
                <Form>
                    <Field
                      component={Select}
                      name="activeUsers"
                      multiple
                      required
                      inputProps={{
                        name: 'activeUsers',
                        id: 'activeUsers',
                      }}
                      renderValue={(selected) => (
                        <div  className={classes.chips}>
                          {selected.map((value) => {
                            return (
                            <Chip key={value.id} label={value.name}  className={classes.chip} />
                          )})}
                        </div>
                      )}
                    >
                      {userArr.map((user) => (
                        <MenuItem key={user.id} value={user}>
                          {user.name}
                        </MenuItem>
                      ))}
                    </Field>
               </Form>
             )}
      </Formik>
`
So essentially the initial Values display fine but when opening the menu the already added items arent highlighted. This is a use-case for editing a Form. Any help will be greatly appreciated.

**Comment by cliedeman** [comment]
Hi @naudej 

Can you create a sandbox example from here https://material-ui.com/r/issue-template?
If I have a working example in material ui I might be able to works backwards and create a formik-material-ui example

**Comment by naudej** [comment]
Hi @cliedeman , here is a sandbox example (https://codesandbox.io/s/lively-bush-jsidz?file=/index.js). Any assistance you could provide would be greatly appreciated,

**Comment by cliedeman** [comment]
Hi @naudej 
Here is a working example - https://codesandbox.io/s/serene-villani-1dgue.

I simplified it a bit but the core issue is that by defining a new array for active users vs userArr they have different identities.

Here is the line where everything goes wrong
https://github.com/mui-org/material-ui/blob/v4.11.0/packages/material-ui/src/Select/SelectInput.js#L171

This code is key

```tsx
  const initialValues = useMemo(() => {
    return {
      activeUsers: users.filter((u) => activeUsers.includes(u.id))
    };
  }, []);
```

**Comment by naudej** [comment]
@cliedeman Thanks this works great!! Appreciate the assistance
