### ISSUE TITLE
Error message is shown as helperText even when TextField is not touched yet

### ISSUE THREAD

**Issue by cherniavskii** [stackworx/formik-material-ui#22]
Hi,
I just came across your library and noticed potentially unwanted behavior of `TextField` component.

## Steps to reproduce:
1. Open https://codesandbox.io/s/z65oq5q9y3
2. Type few letters in `email` TextField (so the email is not valid)
3. See helperText. Note, that this field is not highlighted with error color yet

## Current behavior:
Error message appears instead of helperText

![textfield](https://user-images.githubusercontent.com/13808724/44330080-6735d200-a466-11e8-8dc6-f0e7d7933710.png)

## Expected behavior:
While field is not touched, there should be no error message in helperText.

## Rationale:
User can pass custom helperText. For example, for email field it can be `helperText="e.g. john@doe.com"`.

This helperText should be overridden by error message only when field is touched, so user can always see helperText while typing the first time.

Let me know what do you think about that.
I'll submit a PR if you agree ;)

**Comment by cliedeman** [comment]
Hello,

if you are saying this [line](https://github.com/stackworx/formik-material-ui/blob/master/src/TextField.tsx#L27) should become 

`helperText: touched[name] && errors[name] ? errors[name] : props.helperText`

Then that makes perfect sense to me. I would like this library to be as intuitive as possible and mostly do the expected thing (as much as that varies wildly in practice). 

Please send the PR :)

Ciaran

**Comment by cherniavskii** [comment]
Yeah, that's exactly what I was going to suggest ;)

**Comment by cliedeman** [comment]
Ah that was me messing around with beta channels... It didn't go well.


Release in 0.0.8

I have created a new ticket #24  to do automated releases when I have time
