### ISSUE TITLE
how to enable multiple 

### ISSUE THREAD

**Issue by drtapha** [stackworx/formik-material-ui#224]
when i set the select to multiple. i have this error Material-UI: The `value` prop must be an array when using the `Select` component with `multiple` .  How to do the multiple ?

**Comment by refex** [comment]
i have the same problem

**Comment by cliedeman** [comment]
Hi @drtapha. Is your initial value an array?

**Comment by drtapha** [comment]
I set an array as initial value and i fix the problem
