### ISSUE TITLE
Is it kosher to have Nested Stepper components within individual Step Components (i.e. Stepper 1.0 > Step 1 > Stepper 2.0 > Step 1 + Step 2 ...)

### ISSUE THREAD

**Issue by CharlestonREM** [stackworx/formik-material-ui#231]
A question circa these two stack questions:

1. https://ux.stackexchange.com/questions/102734/how-would-you-represent-the-progression-of-steps-within-steps
2. https://stackoverflow.com/questions/64883191/how-do-i-implement-nested-steps-within-an-individual-material-ui-stepper-step-a

**Comment by CharlestonREM** [comment]
# Codesandbox of an example
Click [here ](https://codesandbox.io/s/blissful-star-d9xj8?file=/src/pages/index.tsx)to see the codesandbox.

## Ensuing Console Warnings

Checking in the console I find that the following warnings occur when I nest custom Stepper Component within a custom Step Component.

### Here's My Code
![image](https://user-images.githubusercontent.com/74624127/102934264-c7dbdc00-4471-11eb-9544-9a1328a79fc0.png)

### Here's the Warnings
```
Warning: validateDOMNesting(...): <form> cannot appear as a descendant of <form>.
    in form (created by Form)
    in Form (at pages/index.tsx:169)
    in Formik (at pages/index.tsx:143)
    in FormikStepper (at pages/index.tsx:92)
    in FormikStep (at pages/index.tsx:64)
    in form (created by Form)
    in Form (at pages/index.tsx:169)
    in Formik (at pages/index.tsx:143)
    in FormikStepper (at pages/index.tsx:23)
    in div (created by ForwardRef(CardContent))
    in ForwardRef(CardContent) (created by WithStyles(ForwardRef(CardContent)))
    in WithStyles(ForwardRef(CardContent)) (at pages/index.tsx:22)
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by ForwardRef(Card))
    in ForwardRef(Card) (created by WithStyles(ForwardRef(Card)))
    in WithStyles(ForwardRef(Card)) (at pages/index.tsx:21)
    in Home (at _app.tsx:33)
    in div (created by Styled(MuiBox))
    in Styled(MuiBox) (at _app.tsx:32)
    in div (created by ForwardRef(Container))
    in ForwardRef(Container) (created by WithStyles(ForwardRef(Container)))
    in WithStyles(ForwardRef(Container)) (at _app.tsx:31)
    in ThemeProvider (at _app.tsx:22)
    in MyApp
    in ErrorBoundary (created by ReactDevOverlay)
    in ReactDevOverlay (created by Container)
    in Container (created by AppContainer)
    in AppContainer
    in Root
```

## Proposed Solutions

I suspect[ this stack](https://stackoverflow.com/a/52884233/14657615) is helpful. Screenshot below :
![image](https://user-images.githubusercontent.com/74624127/102934429-15f0df80-4472-11eb-9c6a-9c7dfc2515ef.png)

**Comment by cliedeman** [comment]
@CharlestonREM I don't see the issue in the example anymore. Has this been fixed?

**Comment by CharlestonREM** [comment]
@cliedeman , yes sorry for late reply:  it's been fixed for now. thanks so much!

**Comment by CharlestonREM** [comment]
i can also post later on the solution i opted for, but time is crunched for me, so i won't promise anything.
