### ISSUE TITLE
custom onBlur not triggered when removing AutoComplete chip. 

### ISSUE THREAD

**Issue by justlevine** [stackworx/formik-material-ui#235]
I'm trying to trigger a custom `onBlur` when removing a multiselect option (i.e. autocomplete chip). However, only the default formik `onBlur` is called. 

E.g.:

```jsx
import { useField, Field } from 'formik';
import { Autocomplete } from 'formik-material-ui-lab';
import { TextField } from '@material-ui/core';

export default AutoCompleteField = ( props ) => {
	const [ field, meta, helpers ] = useField( props.name );

	return (
		<Field
			name={ name }
			component={ Autocomplete }
			autoComplete={ true }
			autoSelect={ true }
			multiple={true}
			options={ options }
			onBlur={ ( event ) => {
				field.onBlur( event );
				if ( ! meta.error ) {
					// IRL perform GraphQL mutation
					console.warn( field.value );
				}
			} }
			renderInput={ ( params ) => (
				<TextField
					{ ...params }
					error={ !! meta.touched && !! meta.error }
					helperText={ !! meta.error ? meta.error : description }
					label={ label }
					variant="outlined"
					size={ size }
					fullWidth
					required={ required }
				/>
			) }
		/>
	);
}
```
In the above example, `field.value` will only get logged after an option is added (and the field is deselected). However, if a selected option is deleted (and the field is then deselected), nothing is logged to the console.

**Comment by cliedeman** [comment]
Hi @justlevine ,

I don't see any formik-material-ui code being used here? This should probably be asked on stackoverflow or the material-ui library

**Comment by justlevine** [comment]
@cliedeman the `<Field component={Autocomplete} />` is from formik-material-ui-lab. My assumption is that the Autocomplete component isn't accepting the custom onBlur() and is instead using the default - which would make it a bug, no?

**Comment by cliedeman** [comment]
Hi @justlevine my mistake I missed that 

I created a codesandbox - https://codesandbox.io/s/inspiring-glade-rv9g7

For me the blur alert gets fired
