### ISSUE TITLE
Library doesn't support tree shaking, as well as breaks material-ui's own tree shaking

### ISSUE THREAD

**Issue by CodySchaaf** [stackworx/formik-material-ui#244]
As you can see here: 

https://github.com/CodySchaaf/material-ui-formik

When you include any of this libraries components it ends up pulling in all of `material-ui`'s components that are imported into `formik-material-ui` because of how the library builds all of the exports into a single dist/index.js file.

Just material-ui:

<img width="1673" alt="not using formik-material-ui" src="https://user-images.githubusercontent.com/3959940/111209393-31f3b100-8589-11eb-8a9f-80804110d511.png">

After adding material-ui-formik

<img width="1677" alt="using formik-material-ui" src="https://user-images.githubusercontent.com/3959940/111209422-3750fb80-8589-11eb-86e0-32010726a46d.png">

**Comment by webappcoding** [comment]
Same issue here

**Comment by cliedeman** [comment]
does the issue still happen if you import the components directly without using the index?
You will have the same isue if you import directly from the material ui top level

**Comment by CodySchaaf** [comment]
@cliedeman No you won't. In my first screen shot I am importing the components from the top level (as you can see in the linked repo https://github.com/CodySchaaf/material-ui-formik/commit/b0a81b254efff8f0300bc08a91210b040f845f81), and only the ones I use are in the bundle. Most modern libraries are bundled in a way that that is supported without issue.  See https://material-ui.com/guides/minimizing-bundle-size/#when-and-how-to-use-tree-shaking 

> If you're using ES6 modules and a bundler that supports tree-shaking (webpack >= 2.x, parcel with a flag) you can safely use named imports and still get an optimised bundle size automatically:
```
import { Button, TextField } from '@material-ui/core';
```

Idk if it as simple as adding `"sideEffects": false` to your package.json like material-ui has, or if you need additional rollup config.

**Comment by CodySchaaf** [comment]
It also doesn't look like you can actually hit anything but the index for this project because the package doesn't have anything else. 
<img width="334" alt="Screen Shot 2021-08-20 at 3 04 09 PM" src="https://user-images.githubusercontent.com/3959940/130293322-97a58d4f-658e-44f6-9e87-2f926b46e867.png">
Not sure if you would have better luck using the es6 one, but like with other packages it should pick that one automatically if it is more appropriate.

**Comment by CodySchaaf** [comment]
ah just kidding webpack already intuitively picks the es6 module one https://github.com/webpack/webpack/blob/52184b897f40c75560b3630e43ca642fcac7e2cf/lib/WebpackOptionsDefaulter.js#L337 
<img width="952" alt="Screen Shot 2021-08-20 at 3 46 07 PM" src="https://user-images.githubusercontent.com/3959940/130296622-90c2a49c-d9c5-47b8-8952-f30d8e036468.png">

**Comment by cliedeman** [comment]
@CodySchaaf try 
```tsx
import { Checkbox } from 'formik-material-ui/dist/Checkbox';
```

**Comment by cliedeman** [comment]
if you confirm that works then you can use an eslint rule like

```js
"no-restricted-imports": ["error", "formik-material-ui"],
```

to ban the top level import

**Comment by cliedeman** [comment]
@CodySchaaf try formik-material-ui@4.0.0.alpha.1
