### ISSUE TITLE
Question: what is the purpose of `createComponent`?

### ISSUE THREAD

**Issue by cherniavskii** [stackworx/formik-material-ui#25]
Hi Ciaran,

I'm wondering, what is the purpose of `createComponent` function?
It seems to be over-complicated, particularly `InputComponent` class component with `getRenderedComponent` method (which isn't used anyway).

**Comment by cliedeman** [comment]
`getRenderedComponent ` can probably be safely be removed. It was originally copied from here: https://github.com/erikras/redux-form-material-ui/blob/master/src/createComponent.js. 

On reasons to keep createComponent: I should probably allow passing through a fieldRef using the modern `React.createRef()` method for people who want access to the inner object.

**Comment by cliedeman** [comment]
Please go ahead. I think the simplified code will be easier to follow and customize.
