### ISSUE TITLE
support for material-ui v5

### ISSUE THREAD

**Issue by MridulaKamath** [stackworx/formik-material-ui#269]
Is this project working on supporting material-ui v5? I feel the only change would be to update dependencies. It shouldn't impact the actual code.

**Comment by cliedeman** [comment]
Hi @MridulaKamath I will cap the version to v4 on the current major and then release an update that requires v5. I am sure there will be some slight changes and don't want those to affect existing v4 users. I am just waiting for it to hit release candidate

**Comment by cliedeman** [comment]
Also there are breaking changes. Some components moved from labs to core.

**Comment by MridulaKamath** [comment]
@cliedeman Thanks for the quick reply. I forgot that the pickers did get moved.

I'll be closing this, as I've received an answer to my question. Thanks!
