### ISSUE TITLE
Console Warning: The Autocomplete component was moved from the lab to the core in MUI v5

### ISSUE THREAD

**Issue by michaelpward** [stackworx/formik-material-ui#270]
In Material-UI v5, the `<Autocomplete />` component is no longer imported from the `/lab` as it [has been  moved to the core](https://next.material-ui.com/components/autocomplete/).

As a result, formik-material-ui is causing a warning in the console when used with Material-UI v5:

> Material-UI: The Autocomplete component was moved from the lab to the core.
>
> You should use `import { Autocomplete } from '@material-ui/core'`
> or `import Autocomplete from '@material-ui/core/Autocomplete'`

![image](https://user-images.githubusercontent.com/1354616/128041267-fc46bf4f-e151-46c4-9d7d-65601777cb63.png)

**Comment by cliedeman** [comment]
will bre resolve in #291
