### ISSUE TITLE
Allow default `onChange` to be overridden

### ISSUE THREAD

**Issue by scardetto** [stackworx/formik-material-ui#39]
Is there a way to override the contained input's `onChange` handler?

I would like to do something like the following...

```
import { TextField } from 'formik-material-ui'

<Formik
  render={({ handleChange }) => (
    ...
    <Field
      label="Email"
      name="email"
      type="email"
      component={TextField}
      onChange={e => {
        // Call the default handler...
        handleChange(e)
        // Then do something custom...
      }}
    />
    ...
  )
/>
```

From what I gather, the field's default `onChange` always takes precedence.

Is this currently possible, and if so, is there a recommended way to do this?

Thanks!

**Comment by scardetto** [comment]
This worked great. Thanks for the help!

**Comment by acadgildjunior** [comment]
Is there a better way of doing this now?
