### ISSUE TITLE
Select with multiple is not Working 

### ISSUE THREAD

**Issue by viveknaragude** [stackworx/formik-material-ui#47]
**Material-UI: the `value` property must be an array when using the `Select` component with `multiple**

<Field
                name='events'
                component={Select}
                multiple
                value={["a", "b"]
                onChange={this.handleChange}>
                <MenuItem key="name" value="name">
                  <ListItemText primary="1" />
                </MenuItem>
                <MenuItem key="name" value="name">
                  <ListItemText primary="2"/>
                </MenuItem>
              </Field>

**Comment by viveknaragude** [comment]
Its not working with value property

**Comment by cliedeman** [comment]
Released in v0.0.19
