### ISSUE TITLE
CodeSandbox is broken

### ISSUE THREAD

**Issue by tgrrr** [stackworx/formik-material-ui#54]
The codesandbox is broken.

The fix is here: 
https://codesandbox.io/s/zqwv712423
Adding a name to the select component helps
Then there's a value error in console. I've added something to remove the error, but it probably needs to be updated to a controlled value.

I didn't fix the final problem, which is there being two dropdown elements on the select:

![zqwv712423_-_codesandbox](https://user-images.githubusercontent.com/4689707/50744683-69fc5c80-1279-11e9-8551-c8f78cae60ce.jpg)

**Comment by glowkeeper** [comment]
+1. Any chance you could fix the code sandbox?

Or, could I see the source for the demo? I want to see how you get the select box working...

**Comment by cliedeman** [comment]
It's been Fixed. Select is a bit of a tough one. I recommend you use the TextField with select variation like in the sandbox
