### ISSUE TITLE
How to configure TextField?

### ISSUE THREAD

**Issue by ianeinser** [stackworx/formik-material-ui#58]
Hello,

i want to use some TextField parameters such as variant="outlined", fullwidth etc.. How to configure that?

**Comment by johnraz** [comment]
This may be a bit late but here is how I made it work:

First, you need to declare a "customized" version of the `TextField
```
import MUITextField from "@material-ui/core/TextField"
import {fieldToTextField} from "formik-material-ui";

const OutlinedTextField = (props) => (
    <MUITextField
        {...fieldToTextField(props)}
        variant={"outlined"}
    />
);
```

And later on in your `Field` definition:

```
<Field
    component={OutlinedTextField}
/>
```

I hope that helps 😉

**Comment by johnraz** [comment]
@cliedeman out of curiosity, is there any better way to achieve this?

**Comment by cliedeman** [comment]
This worked for me:

```          <Field
            label="Outlined"
            name="outlined"
            variant="outlined"
            component={TextField}
          />```

Any extra props are passed [directly](https://github.com/stackworx/formik-material-ui/blob/master/src/TextField.tsx#L26) to the material ui text field.

**Comment by johnraz** [comment]
Wow, splendid! I have no idea how I missed that but thanks a ton!

I guess this can be closed now 👍

**Comment by cliedeman** [comment]
No problem 👍
