### ISSUE TITLE
Labels and initial values overlap

### ISSUE THREAD

**Issue by ptrobert** [stackworx/formik-material-ui#59]
we are using Query component to fetch details and populating initialvalues, all the values are being set but
the labels (which are displayed as placeholders before entering any values) remain same.

That is both labels and initial values are overlapping in the text field.

we have supplied enablereinitialize flag also.

**Comment by cliedeman** [comment]
Can you provide a code sandbox example?

**Comment by octopuss** [comment]
Hi I have same problem.
see example code here https://codesandbox.io/s/qvkw3xm13q
In my real world example I have some data loaded async and some of them are passed to Formik directly.

**Comment by cliedeman** [comment]
@octopuss thanks for the codesandbox. I am not sure this is a problem with the library. 

The initialValues being set to empty strings is somewhat mandatory. 
If you check the console in the first example you will see this error in the log:

`Warning: A component is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components`

**Comment by octopuss** [comment]
@cliedeman yeah, I realized that after reading the docs, so I've edditted the comment and added "solution"
It is not the problem with the library, but I'll keep the comment if someone else will need the guidance.

**Comment by gdSuhail** [comment]
https://stackoverflow.com/a/54226170/6613333

**Comment by nishant-k-290195** [comment]
![image](https://user-images.githubusercontent.com/26035708/163168356-f8a255e7-028e-40e2-b342-af79820e1af3.png)
