### ISSUE TITLE
Select multiple schema errors

### ISSUE THREAD

**Issue by djkingh01** [stackworx/formik-material-ui#65]
Hello,

It is not showing schema errors with select multiple on form submit. 
`
<FormControl fullWidth>
                        <InputLabel htmlFor="tags">Tags</InputLabel>
                        <Field
                            type={"text"}
                            name="tags"
                            component={Select}
                            multiple={true}
                            inputProps={{
                                name: 'tags',
                                id: 'tags',
                            }}
                            fullWidth
                        >
                            <MenuItem value="dogs">Dogs</MenuItem>
                            <MenuItem value="cats">Cats</MenuItem>
                            <MenuItem value="rats">Rats</MenuItem>
                            <MenuItem value="snakes">Snakes</MenuItem>
                        </Field>
                    </FormControl>
`

**Comment by cliedeman** [comment]
Hello,

The select field [api](https://material-ui.com/api/select/) does not have any provision for error display. You will have to use something like formik [ErrorMessage](https://jaredpalmer.com/formik/docs/api/errormessage) to display the error 

Ciaran

**Comment by scott-mcnulty** [comment]
@djkingh01 To display the select as having an error I wrapped my select in a FormControl like so:

```js
<FormControl
  error={errors.myField}
  fullWidth={true}
>
  <Field
    name={`myField`}
    component={Select}
  >
    {mySelectItems}
  </Field>
  {errors.myField && <FormHelperText>{errors.myField}</FormHelperText>}
</FormControl>
```

This way you get the nice red color on the input like a text field would with an error
