### ISSUE TITLE
Switch initially checked

### ISSUE THREAD

**Issue by edorivai** [stackworx/formik-material-ui#66]
Given the following truncated example, I would expect the switch to be initially turned on:

```js
import { Switch } from 'formik-material-ui';

initialValues = { myField: true }

<FormControlLabel
	control={<Field name="myField" type="checkbox" component={Switch} />}
	label="My Field"
/>
```

I noticed issue #41 and PR #42 but couldn't get it to work out of the box. 

I added some logs to the `Switch` component, and noticed that `field.value === undefined`. So I added `value={values.myField}` as a prop to the `Field`, and it works now. Not sure if this is how it's supposed to work.

Working version:

```js
<Formik render={({ values }) =>
    <form>
        <FormControlLabel
            control={<Field name="myField" value={values.myField} type="checkbox" component={Switch} />}
            label="My Field"
        />
    </form>
</Formik>
```

versions:
```
@material-ui/core@3.9.3
formik-material-ui@0.0.16
react@16.8.6
```

**Comment by cliedeman** [comment]
Not sure what is going wrong. Without a full example it looks like `initialValues` is not being passed to formik?

I have updated the [sandbox](https://codesandbox.io/s/915qlr56rp) to contain an example

**Comment by edorivai** [comment]
Oh god, it's the `type="checkbox"`. Just confirmed it in your sandbox.

**Comment by Gabriellvs60** [comment]
**In 2020!**
```export default function SwitchInput({ name, label, handleChange }: Props) {
  const [field, meta] = useField(name);
  //handleChange by useFormikContext
  return (
    <FormControlLabel
        control={<Switch checked={field.value} onChange={handleChange(name)} />}
        label={label}
      />
  );
}```

**Comment by hotcakedev628** [comment]
Me either!
```
<Formik
      initialValues={{
        isVisible: term.is_visible || true,
      }}
      validationSchema={Yup.object().shape({
        isVisible: Yup.bool()
      })}
      onSubmit={async (values, {
        resetForm,
        setErrors,
        setStatus,
        setSubmitting,
      }) => {
         ...
      }}
    >
      {({
        errors,
        handleBlur,
        handleChange,
        handleSubmit,
        isSubmitting,
        setFieldValue,
        touched,
        values
      }) => (
          <form
            className={clsx(classes.root, className)}
            onSubmit={handleSubmit}
            {...rest}
          >
             ...
                   <Switch
                      checked={values.isVisible}
                      color="secondary"
                      edge="start"
                      name="isVisible"
                      onChange={handleChange}
                      value={values.isVisible}
                    />
             ...
```

This is not working!
What value should I pass to Switch value?

**Comment by Jule-** [comment]
Ok this one was tricky! I think a `switch` alias of `checkbox` should exist or even just a mention in the documentation, I can't find it and it is misleading since all seems to work except the initial value! 🙂

**Comment by sachintbits** [comment]
You can access setFieldValue and values from render props.

`<Switch
                            checked={values.offer}
                            onChange={(e) => {
                              setFieldValue(
                                'offer',
                                e.target.checked,
                                false 
                              )
                            }}
                            color="primary"
                            name="offer"
                            inputProps={{ 'aria-label': 'offer status' }}
                          />`

Whenever you need to modify the values check to see the available helper functions. Most of the use cases will be ready to use. If you couldn't find any way, then create your own.
