### ISSUE TITLE
Runtime error with Checkbox and Material-UI v4

### ISSUE THREAD

**Issue by bard** [stackworx/formik-material-ui#67]
Just a heads-up. This may be due to changes in Material-UI v4 alpha.

The following:

```
<Field
  Label={{ label: 'Do you confirm?" }}
  name='confirmation'
  component={CheckboxWithLabel}
  color='primary'
/>
```

At runtime was causing:

```
Warning: Failed prop type: Invalid prop `checked` of type `string` supplied to `ForwardRef(Checkbox)`, expected `boolean`.
    in ForwardRef(Checkbox) (created by WithStyles(ForwardRef(Checkbox)))
    in WithStyles(ForwardRef(Checkbox)) (created by FormikMaterialUICheckboxWithLabel)
    in label (created by ForwardRef(FormControlLabel))
    in ForwardRef(FormControlLabel) (created by Context.Consumer)
    in WithFormControlContext(ForwardRef(FormControlLabel)) (created by WithStyles(WithFormControlContext(ForwardRef(FormControlLabel))))
    in WithStyles(WithFormControlContext(ForwardRef(FormControlLabel))) (created by FormikMaterialUICheckboxWithLabel)
```

Changing this:

https://github.com/stackworx/formik-material-ui/blob/8d8b6abf18e6ce9f95020eb6f9ce9f9c6b6b8e10/src/Checkbox.tsx#L26

To:

```
    checked: field.value
```

That is, leaving the boolean value alone, not converting it to string, fixed it.

**Comment by corydeppen** [comment]
This is still an issue using `@material-ui/core@4.0.0-beta.1`. Based on the [`checked` PropType](https://github.com/mui-org/material-ui/blob/next/packages/material-ui/src/Checkbox/Checkbox.js#L95) now being limited to `bool`, the recommendation by @bard seems appropriate.

I'm happy to submit a PR if you'd like.

This will presumably require a major version bump due to the breaking change.

**Comment by cliedeman** [comment]
I think we should only merge the PR when 4 is released as we should bump the peer dependency 4.0 >=.

In the meantime you can use this:

```
import {
  Checkbox as MuiCheckbox,
} from '@material-ui/core';
import {
  CheckboxProps,
  fieldToCheckbox,
} from 'formik-material-ui';


const Mui4Checkbox = (props: CheckboxProps) => {
  return (
    <MuiCheckbox {...fieldToCheckbox(props)} checked={props.field.value} />
  );
};
```

**Comment by MacMuffin** [comment]
Heyho,

I think it's time to merge the PR, isn't it? 4.0 is out since last week.

**Comment by johnraz** [comment]
I couldn't find a PR so I went ahead an created it here: #75

**Comment by MacMuffin** [comment]
A huge thanks! :-)

**Comment by johnraz** [comment]
Yea, @cliedeman thanks for your time 😉 👍
