### ISSUE TITLE
The placeholder/label does not fill an empty multi select control

### ISSUE THREAD

**Issue by mrosm20** [stackworx/formik-material-ui#70]
Example code

```
<FormControl required className={classes.formControls}>
                        <InputLabel  htmlFor="classifications-label">Classification</InputLabel>
                        <Field
                            id="assetClass"
                          //  name="assetClass"
                            label="Classification"
                            placeholder="Classification"
                            helperText="Please select classification"
                            margin="normal"
                            component={Select}
                            inputProps={{
                              name:"assetClass",
                              id: 'classifications-label',
                            }}
                        >
                          {
                          productAggregate.map(option => (
                          <MenuItem key={option.value} value={option.value}>
                            {option.value}
                          </MenuItem>
                          ))
                        }
                        </Field>
                      </FormControl>
```

if I change the Select Component to the materials core component. The label properly fills the empty component. 

Wondering if this is  a bug or I'm doing something wrong.

If you goto the materials-ui docs demo the first drop-down in the examples works perfect. If you select and unselect the items you will see the label fill the empty control.

https://material-ui.com/demos/selects/

Even in the samples that you have provided the TextFields works perfectly, but the multi select does not.

**Comment by tobytraylor** [comment]
I'm running into this same issue.

**Comment by cliedeman** [comment]
Looks like this is just a bit of surprising behaviour and my storybook exactly was not correct.

I have added another example [here](https://stackworx.github.io/formik-material-ui/?path=/story/formik--select). Looks like the displayEmpty property will get you the behaviour you want
