### ISSUE TITLE
How to use 3rd party date time packages?

### ISSUE THREAD

**Issue by chaitanya1019** [stackworx/formik-material-ui#74]
Hi, i am using TextField(type=date) Component to display date. Can someone help on how to use [material-ui-pickers](https://www.npmjs.com/package/material-ui-pickers) package with formik-material-ui and still get all the benefits of this repo.

**Comment by cliedeman** [comment]
Because the pickers expect name and onChange you can use them directly with almost no changes.

```
<Field name="date" component={DatePicker} />
<Field name="time" component={TimePicker} />
<Field name="dateTime" component={DateTimePicker} />
```

[Example](https://codesandbox.io/embed/reverent-rain-zfpfo)

**Comment by oscar-b** [comment]
https://material-ui-pickers.dev/guides/form-integration

**Comment by cliedeman** [comment]
@oscar-b thanks linking for that
