### ISSUE TITLE
Formik material-ui doesn't link to react state in component

### ISSUE THREAD

**Issue by tgrrr** [stackworx/formik-material-ui#76]
Big fan,

When we get/set the state with a Formik field, we'd expect to be able to do so within the component itself.

This is how it works with formik itself. However, it doesn't work with the text, switch, or select component.

[Here's the difference as a code sandbox demo](https://codesandbox.io/s/formik-materialui-toggle-demo-2ckqf)

Trying to do so results in the following error:

> Input elements must be either controlled or uncontrolled (specify either the checked prop, or the defaultChecked prop, but not both). Decide between using a controlled or uncontrolled input element and remove one of these props. More info: https://fb.me/react-controlled-components

**Comment by cliedeman** [comment]
Hi @tgrrr, Thanks for the example but I am struggling to see where it is breaking.

Is there a specific reason you have state outside of formik?

`const [toggle, setToggle] = useState(false);` looks very strange to me

**Comment by tgrrr** [comment]
I'm not sure why people wouldn't want control to get + set state outside of Formik itself.

We don't just interact with form components when we hit a submit button. 

Some components interact with one another, and other components. Eg. Setting the value on a checkbox hides another components.

The example you copied is just managing state with hooks. It can be swapped out for `setState`, redux, or any other state management. 

The point is that there's freedom to interact with react's state in Formik. Why wouldn't this also exist in Formik-Material?

**Comment by cliedeman** [comment]
Ah I think I get it now. The question could be why do I explicitly exclude these [fields](https://github.com/stackworx/formik-material-ui/blob/master/src/Checkbox.tsx#L12)

```
export interface CheckboxProps
  extends FieldProps,
    Omit<
      MuiCheckboxProps,
      'form' | 'checked' | 'defaultChecked' | 'name' | 'onChange' | 'value'
    > {}
```

The reason is that I want exactly one place for state to be stored. That being said modifying state outside of formik happen often enough. 

Would this pattern work for you?
https://codesandbox.io/s/goofy-jepsen-2s4f4

Otherwise you can always create your own special case [field](https://github.com/stackworx/formik-material-ui#custom-onchange).

Ciaran

**Comment by tgrrr** [comment]
Yes, I feel like that is exactly the question, thanks.

> Would this pattern work for you?
Which pattern do you mean?

**Comment by tgrrr** [comment]
Why was this closed @cliedeman?

**Comment by cliedeman** [comment]
Because it’s working as intended. This library delegates all state management to formik.
