### ISSUE TITLE
Please add AutoComplete Component to the library.

### ISSUE THREAD

**Issue by chaitanya1019** [stackworx/formik-material-ui#77]
Auto Complete component would be great add on to this library.
https://github.com/JedWatson/react-select
https://github.com/moroshko/react-autosuggest

**Comment by cliedeman** [comment]
I don't the library should choose an autocomplete implementation. We will probably follow suite with material-ui core and leave this up to the user. https://material-ui.com/components/autocomplete/. I am open to adding a storybook example for them though

**Comment by chaitanya1019** [comment]
> I don't the library should choose an autocomplete implementation. We will probably follow suite with material-ui core and leave this up to the user. https://material-ui.com/components/autocomplete/. I am open to adding a storybook example for them though

Yes..please add storybook example for autocomplete. It's one of the most used feature in a form.
