### ISSUE TITLE
disabled fields are not posted

### ISSUE THREAD

**Issue by oliversturm** [stackworx/formik-material-ui#81]
When posting a form using its `method` and `action` attributes, `TextField` instances handled by formik-material-ui are not included in the posted form data. I tracked this problem to [this line](https://github.com/stackworx/formik-material-ui/blob/a002f4b676edbe9cfc980c8e1e0fa148a9c10ed0/src/TextField.tsx#L33) where the control is disabled if `isSubmitting` is true. I believe the same mechanism is used for controls other than the `TextField`.

Fields created by Formik without the involvement of formik-material-ui are included in post data correctly. I haven't checked to see whether they are not disabled at all (although at a quick glance the Formik source code doesn't seem to contain the term `disabled`) or whether they are disabled at a different point in time. In any case it is clearly formik-material-ui which breaks the form post mechanism.

Since material-ui doesn't support `readOnly`, I'm not sure there's an alternative. I suggest removing the dependency on `isSubmitting` from the `disabled` setting.

**Comment by cliedeman** [comment]
Can you provide a code sandbox example? In my testing this worked as expected.

Ciaran

**Comment by oliversturm** [comment]
Here is a sandbox: https://codesandbox.io/s/github/oliversturm/demo-formik-material-ui-form-post/tree/master/

* If you submit the first two forms in the view, the terminal output shows the submitted data
* If you submit the third form (which uses the formik-material-ui TextField), you will see an empty POST body in the terminal

Please note that the sandbox is set up to run the React app out of the build folder, so changes are not recognized automatically.

**Comment by oliversturm** [comment]
Just updated the sample to include a formik Field without a component attribute. Now the only difference between form 3 (which works) and 4 (which doesn't work) is that attribute.

**Comment by oliversturm** [comment]
Any updates? Have you been able to reproduce?

**Comment by oliversturm** [comment]
Never mind, I see that a workaround has become possible with https://github.com/stackworx/formik-material-ui/commit/73a98c4a4049381683d8eec3d3962c70247dd3d9

For posterity - I can now explicitly set `disabled={false}` on a `Field` to make sure it won't be disabled during submission.

**Comment by cliedeman** [comment]
Hi @oliversturm 

I gave this quite a bit of thought and wanted to reply anyway for future readers.

In short when using an action to submit a form disabled fields are not included and this is correct per spec.

That being said I believe people using action to submit forms (aka full page submit) it a bit of an edge case. Most projects use an Ajax submit and I feel the benefits of the disabled during submission here outweigh the drawbacks.

Ciaran

**Comment by oliversturm** [comment]
Thanks, @cliedeman - I understand your choice and it's fine with me. Also agreed that old-fashioned form submits are not very common these days! 

What bothers me a bit is that formik-material-ui behaves differently in this regard than standard Formik does.
