### ISSUE TITLE
`InputBase` with name as value

### ISSUE THREAD

**Issue by Wunsz** [stackworx/formik-material-ui#90]
Why `InputBase`:
[https://github.com/stackworx/formik-material-ui/blob/master/src/InputBase.tsx](https://github.com/stackworx/formik-material-ui/blob/master/src/InputBase.tsx)

```js
export const fieldToInputBase = ({
  field,
  form: { isSubmitting },
  disabled,
  ...props
}: InputBaseProps): MuiInputBaseProps => {
  return {
    disabled: disabled != undefined ? disabled : isSubmitting,
    ...props,
    ...field,
    value: field.name,
  };
};
```

inputs field name as its value. According to Material UI component demos, this is not a intended behaviour:
[https://material-ui.com/components/text-fields/#customized-inputs](https://material-ui.com/components/text-fields/#customized-inputs)

**Comment by Wunsz** [comment]
I have fixed the error and created a pull request - #91 

Please review.

**Comment by cliedeman** [comment]
Hi @Wunsz 

Can you point me to exactly where it says name should not be passed in? It is definitely present in the API

**Comment by Wunsz** [comment]
Hi @cliedeman 

Please refer to the link: https://material-ui.com/components/text-fields/#customized-inputs
In the example shown the last field is a "naked input":

```jsx
<InputBase
    className={classes.margin}
    defaultValue="Naked input"
    inputProps={{ 'aria-label': 'naked' }}
/>
```

Furthermore in the Component documentation itself: https://material-ui.com/api/input-base/#props
I don't say we shouldn't pass the name altogether. It is in the API but name should be passed to `name` prop and value to `value` prop as in documentation:

Name | Type | Default | Description
-- | -- | -- | --
name | string |   | Name attribute of the input element.
value | any |   | The value of the input element, required for a controlled component.


When we provide input element `name` as `value` it makes the field read only. And this is supposed to be used as a custom form input element base:

> InputBase contains as few styles as possible. It aims to be a simple building block for creating an input. It contains a load of style reset and some state logic.

Furthermore, again from: https://material-ui.com/components/text-fields/#customized-inputs

> Customization does not stop at CSS, you can use composition to build custom components and give your app a unique feel. Below is an example using the InputBase component, inspired by Google Maps.

I hope that it clarifies what I mean.

**Comment by JorgeVV** [comment]
InputBase is currently unusable. PR #91 fixes this bug. Is there any reason why it has not been merged? 😅

**Comment by Wunsz** [comment]
@cliedeman Any progress on this? Where can we a have a merge and release?

**Comment by cliedeman** [comment]
Release in 0.22
