### ISSUE TITLE
Support new 'as' instead of 'component' prop

### ISSUE THREAD

**Issue by mayteio** [stackworx/formik-material-ui#92]
When using the following syntax:

```javascript
<Field
  component={TextField}
  type="email"
  id="email"
  name="email"
  label="Email"
/>
```

You get the error:

`Warning: <Field component> has been deprecated and will be removed in future versions of Formik. Use <Field as> instead. Note that with the 'as' prop, all props are passed directly through and not grouped in 'field' object key.`

What's the policy on deprecations? If I were to submit a pull request, would you want either to work or, since it's going to be deprecated, create a breaking change?

**Comment by cliedeman** [comment]
Hi there.

I think we would just need to update the peer dependencies: `"formik": ">=1.0.0",`.
probably something like `"formik": "^1.0.0" | ^2.0.0`

Then the dev dep would need to be updated and a few formik 2.0 examples should be added.

- as
- New radio group style
- What else?

**Comment by mayteio** [comment]
[Worth noting](https://github.com/jaredpalmer/formik/issues/1046#issuecomment-433259218) jared palmer says <Field> is only kept around for backwards compatibility.

**Comment by cliedeman** [comment]
I see. So what should the new api look like?

useTextField, useSwitch?

Ciaran

**Comment by cliedeman** [comment]
This has been implemented
