### ISSUE TITLE
Switch with Label

### ISSUE THREAD

**Issue by rhuanbarreto** [stackworx/formik-material-ui#94]
First I would like to thank you a lot for this work! This saves lot's of time!

One thing that I didn't find was the label for the switch as it has for the checkbox. How can I make it?

**Comment by cliedeman** [comment]
probably something like:

export interface SwitchWithLabelProps extends SwitchProps {
  Label: Omit<
    MuiFormControlLabelProps,
    'checked' | 'name' | 'onChange' | 'value' | 'inputRef'
  >;
}

```
export const SwitchWithLabel: React.ComponentType<SwitchWithLabelProps> = ({
  Label,
  ...props
}) => (
  <FormControlLabel
    control={<MuiSwitch {...fieldToSwitch(props)} />}
    {...Label}
  />
);
```

**Comment by rhuanbarreto** [comment]
For now I just used: 

```
              <InputLabel
                htmlFor="test"
              >
                <Field
                  name="test"
                  component={Switch}
                  color="primary"
                />
                Label Text
              </InputLabel>
```

But the library could have something integrated like the checkbox.

**Comment by cliedeman** [comment]
Contributions welcome :)

**Comment by Razaik25** [comment]
Hi, 
Can I take this up if no one is working on it?
Thanks

**Comment by cliedeman** [comment]
Sure, go ahead.

**Comment by hotcakedev628** [comment]
Does this not work for you?
                    ```
<Switch
                      checked={values.isChecked}
                      color="primary"
                      edge="start"
                      name="test"
                      onChange={handleChange}
                      value={values.isChecked}
                    />
```

**Comment by rhuanbarreto** [comment]
PR is there for merging for 5 months. Can someone have a look?

**Comment by atlanteh** [comment]
> For now I just used:
> 
> ```
>               <InputLabel
>                 htmlFor="test"
>               >
>                 <Field
>                   name="test"
>                   component={Switch}
>                   color="primary"
>                 />
>                 Label Text
>               </InputLabel>
> ```
> 
> But the library could have something integrated like the checkbox.

Actually according to the [sandbox in the docs](https://codesandbox.io/s/915qlr56rp) the right solution is to use 
```
<FormControlLabel
	control={<Field component={Switch} name="name" />}
	label="Name"
/>
```

Using your solution, clicking on the label doesn't actually changes the switch
