### ISSUE TITLE
Select's `renderValue` prop is typed on Omitted `value` prop

### ISSUE THREAD

**Issue by Krisztiaan** [stackworx/formik-material-ui#95]
In MUI: `renderValue?: (value: SelectProps['value']) => React.ReactNode;`
In this library: `export interface SelectProps extends FieldProps, Omit<MuiSelectProps, 'value'>`

I've added `renderValue?: (value: any) => React.ReactNode;` as a patch for our use-case

**Comment by cliedeman** [comment]
Can you provide an example? I only omit value as formik controls this

```
export interface SelectProps extends Omit<MuiSelectProps, 'value'> {
  name: string;
}```
